/**
 * Config loader — DO NOT EDIT THIS FILE.
 *
 * Extracted from index.ts so it can be unit-tested without resolving the
 * relative ../../_runtime/ paths that only exist in synced task apps.
 */

import { existsSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

const INHERITED_CONFIG_ENV = "MICRO_X_AGENT_CONFIG_JSON";
const ENV_VAR_RE = /\$\{([^}]+)\}/g;

function deepMerge(
  base: Record<string, unknown>,
  overlay: Record<string, unknown>,
): Record<string, unknown> {
  const result: Record<string, unknown> = { ...base };
  for (const [key, value] of Object.entries(overlay)) {
    const current = result[key];
    if (
      current &&
      typeof current === "object" &&
      !Array.isArray(current) &&
      value &&
      typeof value === "object" &&
      !Array.isArray(value)
    ) {
      result[key] = deepMerge(
        current as Record<string, unknown>,
        value as Record<string, unknown>,
      );
    } else {
      result[key] = value;
    }
  }
  return result;
}

function expandEnvVars(value: unknown): unknown {
  if (typeof value === "string") {
    return value.replaceAll(ENV_VAR_RE, (_, name: string) => process.env[name] ?? `\${${name}}`);
  }
  if (Array.isArray(value)) {
    return value.map((item) => expandEnvVars(item));
  }
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value).map(([key, item]) => [key, expandEnvVars(item)]),
    );
  }
  return value;
}

function resolveConfigWithBase(
  data: Record<string, unknown>,
  configDir: string,
): Record<string, unknown> {
  const baseFile = data["Base"];
  if (typeof baseFile !== "string" || baseFile.trim() === "") {
    return data;
  }

  const basePath = resolve(configDir, baseFile);
  if (!existsSync(basePath)) {
    throw new Error(`Base config not found: ${basePath} (referenced via 'Base' key)`);
  }

  const baseData = JSON.parse(readFileSync(basePath, "utf-8")) as Record<string, unknown>;
  const resolvedBase = resolveConfigWithBase(baseData, dirname(basePath));
  const overlay = Object.fromEntries(Object.entries(data).filter(([key]) => key !== "Base"));
  return deepMerge(resolvedBase, overlay);
}

export function loadJsonConfig(configPath?: string): [Record<string, unknown>, string] {
  const inheritedConfig = process.env[INHERITED_CONFIG_ENV];
  if (inheritedConfig) {
    return [
      JSON.parse(inheritedConfig) as Record<string, unknown>,
      `${INHERITED_CONFIG_ENV} (inherited)`,
    ];
  }

  let configPathToLoad: string;
  let source: string;

  if (configPath) {
    configPathToLoad = resolve(configPath);
    source = configPathToLoad;
    if (!existsSync(configPathToLoad)) {
      throw new Error(`Config file not found: ${configPathToLoad}`);
    }
  } else {
    configPathToLoad = resolve(process.cwd(), "config.json");
    source = "config.json";
    if (!existsSync(configPathToLoad)) {
      return [{}, "config.json (defaults)"];
    }
  }

  let data = JSON.parse(readFileSync(configPathToLoad, "utf-8")) as Record<string, unknown>;

  const configFile = data["ConfigFile"];
  if (typeof configFile === "string") {
    const configDir = dirname(configPathToLoad);
    const target = resolve(configDir, configFile);
    if (!existsSync(target)) {
      throw new Error(`ConfigFile target not found: ${target} (referenced from config.json)`);
    }
    data = JSON.parse(readFileSync(target, "utf-8")) as Record<string, unknown>;
    return [
      expandEnvVars(resolveConfigWithBase(data, dirname(target))) as Record<string, unknown>,
      configFile,
    ];
  }

  return [
    expandEnvVars(resolveConfigWithBase(data, dirname(configPathToLoad))) as Record<string, unknown>,
    source,
  ];
}
