/**
 * Task app entry point - DO NOT EDIT THIS FILE.
 *
 * Modes:
 *   Default:    Starts an MCP server exposing the tool(s) defined in task.ts
 *   --run:      Executes one tool directly and prints the result (standalone)
 *   --describe: Prints tool JSON Schema(s) to stdout and exits
 *
 * task.ts may use either shape:
 *   Single tool (legacy): export SERVERS, TOOL_NAME, TOOL_DESCRIPTION,
 *     TOOL_INPUT_SCHEMA, handleTool().
 *   Multiple tools: export SERVERS and TOOLS: ToolDef[] (optionally SERVER_NAME).
 *     See ../../_runtime/src/tool-def.ts.
 */

import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import "dotenv/config";
import { z } from "zod";
import { zodToJsonSchema } from "zod-to-json-schema";

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";

import { McpClient } from "../../_runtime/src/mcp-client.js";
import type { ToolDef } from "../../_runtime/src/tool-def.js";
import { loadJsonConfig } from "./config.js";
import * as task from "./task.js";
import { normalizeTools, type TaskModule } from "./tool-loader.js";

export { loadJsonConfig } from "./config.js";
export { normalizeTools } from "./tool-loader.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const isRunMode = process.argv.includes("--run");
const isDescribeMode = process.argv.includes("--describe");
const isEntrypoint = (() => {
  const argvPath = process.argv[1];
  return argvPath ? resolve(argvPath) === fileURLToPath(import.meta.url) : false;
})();

// In MCP server mode, stdout is the transport - all logging goes to stderr
const log = isRunMode
  ? console.log.bind(console)
  : (...args: unknown[]) => process.stderr.write(args.map(String).join(" ") + "\n");

const TASK_DIR = resolve(__dirname, "..");
const { serverName: SERVER_NAME, servers: SERVERS, tools: TOOLS } = normalizeTools(
  task as TaskModule,
  TASK_DIR,
);

/* ------------------------------------------------------------------ */
/*  Runtime helpers                                                    */
/* ------------------------------------------------------------------ */

interface McpServerConfig {
  command?: string;
  args?: string[];
  env?: Record<string, string>;
}

function loadProfile(): Record<string, unknown> {
  try {
    return JSON.parse(readFileSync(resolve(__dirname, "../profile.json"), "utf-8"));
  } catch {
    return {};
  }
}

function parseConfigPath(): string | undefined {
  const args = process.argv.slice(2);
  const idx = args.indexOf("--config");
  return idx !== -1 && idx + 1 < args.length ? args[idx + 1] : undefined;
}

function parseToolArg(): string | undefined {
  const args = process.argv.slice(2);
  const idx = args.indexOf("--tool");
  return idx !== -1 && idx + 1 < args.length ? args[idx + 1] : undefined;
}

/* ------------------------------------------------------------------ */
/*  MCP client connections (upstream servers)                          */
/* ------------------------------------------------------------------ */

async function connectUpstream(
  config: Record<string, unknown>,
): Promise<Record<string, McpClient>> {
  const mcpConfigs = (config["McpServers"] ?? {}) as Record<string, McpServerConfig>;
  const needed: Record<string, McpServerConfig> = {};
  for (const name of SERVERS) {
    if (mcpConfigs[name]) needed[name] = mcpConfigs[name];
  }

  if (Object.keys(needed).length === 0) {
    if (SERVERS.length > 0) log(`No MCP servers found for: ${SERVERS.join(", ")}`);
    return {};
  }

  log("Connecting MCP servers...");
  const entries = Object.entries(needed).filter(([, cfg]) => cfg.command);
  const results = await Promise.allSettled(
    entries.map(async ([name, cfg]) => {
      const client = new McpClient(name);
      await client.connect(cfg.command!, cfg.args ?? [], cfg.env);
      log(`  ${name}: connected`);
      return [name, client] as const;
    }),
  );

  const connected: Record<string, McpClient> = {};
  for (const result of results) {
    if (result.status === "fulfilled") {
      const [name, client] = result.value;
      connected[name] = client;
    } else {
      log(`  server FAILED: ${result.reason}`);
    }
  }
  log(`${Object.keys(connected).length}/${Object.keys(needed).length} servers connected`);
  return connected;
}

async function shutdownClients(clients: Record<string, McpClient>): Promise<void> {
  if (Object.keys(clients).length === 0) return;
  log("Shutting down MCP servers...");
  await Promise.all(Object.values(clients).map((c) => c.close().catch(() => {})));
  log("Done.");
}

/* ------------------------------------------------------------------ */
/*  MCP server mode (default)                                          */
/* ------------------------------------------------------------------ */

async function runServer(): Promise<void> {
  const [config, source] = loadJsonConfig(parseConfigPath());
  log(`Config: ${source}`);

  const profile = loadProfile();

  // Lazy upstream connection - connect on first tool call, not at startup
  let clients: Record<string, McpClient> | null = null;
  async function getClients(): Promise<Record<string, McpClient>> {
    if (clients) return clients;
    clients = await connectUpstream(config);
    return clients;
  }

  const server = new McpServer(
    { name: SERVER_NAME, version: "0.1.0" },
    { capabilities: { tools: {} } },
  );

  for (const t of TOOLS) {
    server.tool(
      t.name,
      t.description,
      t.inputSchema as z.ZodRawShape,
      async (params: Record<string, unknown>) => {
        const c = await getClients();
        const result = await t.handler(params, c, profile, config);
        return {
          content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }],
        };
      },
    );
  }

  const transport = new StdioServerTransport();
  await server.connect(transport);

  const cleanup = async () => {
    if (clients) await shutdownClients(clients);
    process.exit(0);
  };
  process.on("SIGINT", cleanup);
  process.on("SIGTERM", cleanup);
}

/* ------------------------------------------------------------------ */
/*  Standalone mode (--run)                                            */
/* ------------------------------------------------------------------ */

function selectTool(requested: string | undefined): ToolDef {
  if (requested) {
    const found = TOOLS.find((t) => t.name === requested);
    if (!found) {
      throw new Error(
        `--tool ${requested} not found. Available: ${TOOLS.map((t) => t.name).join(", ")}`,
      );
    }
    return found;
  }
  if (TOOLS.length === 1) return TOOLS[0];
  throw new Error(
    `This app exposes ${TOOLS.length} tools; pick one with --tool <name>. ` +
      `Available: ${TOOLS.map((t) => t.name).join(", ")}`,
  );
}

async function runDirect(): Promise<void> {
  const [config, source] = loadJsonConfig(parseConfigPath());
  console.log(`Config: ${source}`);

  const profile = loadProfile();
  const selected = selectTool(parseToolArg());
  const clients = await connectUpstream(config);

  try {
    let rawParams: unknown = {};
    const args = process.argv.slice(2);
    const paramsIdx = args.indexOf("--params");
    if (paramsIdx !== -1 && paramsIdx + 1 < args.length) {
      rawParams = JSON.parse(args[paramsIdx + 1]);
    }
    const params = z.object(selected.inputSchema as z.ZodRawShape).parse(rawParams) as Record<
      string,
      unknown
    >;

    const result = await selected.handler(params, clients, profile, config);
    console.log(JSON.stringify(result, null, 2));
  } finally {
    await shutdownClients(clients);
  }
}

/* ------------------------------------------------------------------ */
/*  Describe mode (--describe)                                         */
/* ------------------------------------------------------------------ */

function describe(): void {
  const toolsOut = TOOLS.map((t) => ({
    tool_name: t.name,
    description: t.description,
    input_schema: zodToJsonSchema(z.object(t.inputSchema as z.ZodRawShape), {
      target: "jsonSchema7",
      $refStrategy: "none",
    }),
  }));

  const payload: Record<string, unknown> = {
    server_name: SERVER_NAME,
    tools: toolsOut,
  };

  // Soft back-compat shim: single-tool apps also expose top-level singular
  // fields so unupdated readers (older _update_manifest) keep working.
  if (toolsOut.length === 1) {
    payload.tool_name = toolsOut[0].tool_name;
    payload.description = toolsOut[0].description;
    payload.input_schema = toolsOut[0].input_schema;
  }

  process.stdout.write(JSON.stringify(payload));
}

/* ------------------------------------------------------------------ */
/*  Entry                                                              */
/* ------------------------------------------------------------------ */

if (isEntrypoint) {
  if (isDescribeMode) {
    try {
      describe();
    } catch (err) {
      process.stderr.write(`describe failed: ${err}\n`);
      process.exit(1);
    }
  } else if (isRunMode) {
    runDirect().catch((err) => {
      console.error(err);
      process.exit(1);
    });
  } else {
    runServer().catch((err) => {
      process.stderr.write(`Fatal: ${err}\n`);
      process.exit(1);
    });
  }
}
