/**
 * Adapter that normalizes task.ts exports into a canonical
 * (serverName, servers, tools) shape — DO NOT EDIT THIS FILE.
 *
 * Kept in its own module (with no runtime imports) so it can be unit-tested
 * directly without resolving the relative ../../_runtime/ paths that only
 * exist once the template is synced into tools/<task_name>/.
 */

import { basename } from "node:path";

import type { ToolDef } from "../../_runtime/src/tool-def.js";

export interface TaskModule {
  SERVERS?: unknown;
  SERVER_NAME?: unknown;
  TOOLS?: unknown;
  TOOL_NAME?: unknown;
  TOOL_DESCRIPTION?: unknown;
  TOOL_INPUT_SCHEMA?: unknown;
  handleTool?: unknown;
}

export interface NormalizedTask {
  serverName: string;
  servers: string[];
  tools: ToolDef[];
}

export function normalizeTools(mod: TaskModule, taskDir: string): NormalizedTask {
  const servers = Array.isArray(mod.SERVERS)
    ? (mod.SERVERS as unknown[]).filter((s): s is string => typeof s === "string")
    : [];

  let tools: ToolDef[];
  if (Array.isArray(mod.TOOLS) && mod.TOOLS.length > 0) {
    tools = mod.TOOLS as ToolDef[];
  } else if (
    typeof mod.TOOL_NAME === "string" &&
    typeof mod.handleTool === "function"
  ) {
    tools = [
      {
        name: mod.TOOL_NAME,
        description: typeof mod.TOOL_DESCRIPTION === "string" ? mod.TOOL_DESCRIPTION : "",
        inputSchema: (mod.TOOL_INPUT_SCHEMA ?? {}) as ToolDef["inputSchema"],
        handler: mod.handleTool as ToolDef["handler"],
      },
    ];
  } else {
    throw new Error(
      "task.ts must export either TOOLS (multi-tool) or the legacy single-tool " +
        "quadruple (TOOL_NAME, TOOL_DESCRIPTION, TOOL_INPUT_SCHEMA, handleTool).",
    );
  }

  const seen = new Set<string>();
  for (const t of tools) {
    if (!t.name || typeof t.name !== "string") {
      throw new Error(`TOOLS contains an entry with a missing or non-string name`);
    }
    if (seen.has(t.name)) {
      throw new Error(`TOOLS contains duplicate tool name: ${t.name}`);
    }
    seen.add(t.name);
  }

  const serverName =
    typeof mod.SERVER_NAME === "string" && mod.SERVER_NAME
      ? mod.SERVER_NAME
      : tools.length === 1
        ? tools[0].name
        : basename(taskDir);

  return { serverName, servers, tools };
}
