/**
 * Multi-provider LLM helper for generated codegen task apps.
 *
 * Supports Anthropic (native SDK) and OpenAI-compatible providers — OpenAI,
 * DeepSeek, Ollama, and Gemini (via its OpenAI-compatible endpoint) — through a
 * single OpenAI SDK client with a per-provider base URL.
 *
 * Provider + model are chosen by the caller via a `spec`, either:
 *   - "provider/model"  (e.g. "openai/gpt-4.1-mini") to pick a provider, or
 *   - a bare model id   (e.g. "claude-sonnet-4-6") which defaults to Anthropic.
 * A bare model whose leading "<seg>/" is not a known provider (e.g. an Ollama
 * tag "orieg/gemma3-tools:4b-ft") is kept whole as the model under Anthropic;
 * prefix it ("ollama/orieg/...") to route elsewhere.
 *
 * Pricing (for the usage report) is read from the agent's resolved config,
 * forwarded via MICRO_X_AGENT_CONFIG_JSON — the same channel config.ts uses.
 * API keys come from the environment (.env via the task's dotenv import):
 * ANTHROPIC_API_KEY / OPENAI_API_KEY / GEMINI_API_KEY (or GOOGLE_API_KEY) /
 * DEEPSEEK_API_KEY. Ollama needs no key.
 *
 * DO NOT EDIT THIS FILE.
 */

import Anthropic from "@anthropic-ai/sdk";
import OpenAI from "openai";

// ---------------------------------------------------------------------------
// Provider resolution
// ---------------------------------------------------------------------------

export type ProviderName = "anthropic" | "openai" | "deepseek" | "gemini" | "ollama";

export interface ModelSpec {
  provider: ProviderName;
  model: string;
}

/** Minimal message shape tasks use. Content is always plain text. */
export interface ChatMessage {
  role: "user" | "assistant";
  content: string;
}

const KNOWN_PROVIDERS: ReadonlySet<string> = new Set<string>([
  "anthropic",
  "openai",
  "deepseek",
  "gemini",
  "ollama",
]);

/** Read the agent's resolved config forwarded via MICRO_X_AGENT_CONFIG_JSON. */
function inheritedConfig(): Record<string, unknown> {
  const raw = process.env["MICRO_X_AGENT_CONFIG_JSON"];
  if (!raw) return {};
  try {
    return JSON.parse(raw) as Record<string, unknown>;
  } catch {
    return {};
  }
}

/**
 * Resolve a spec to {provider, model}. Splits on the FIRST "/" only when the
 * leading segment is a known provider; otherwise the whole string is the model
 * and the provider defaults to Anthropic (preserving the pre-multi-provider
 * behaviour for bare model ids).
 */
export function resolveSpec(spec: string | ModelSpec): ModelSpec {
  if (typeof spec !== "string") {
    return { provider: spec.provider, model: spec.model };
  }
  const slash = spec.indexOf("/");
  if (slash > 0) {
    const head = spec.slice(0, slash).toLowerCase();
    if (KNOWN_PROVIDERS.has(head)) {
      return { provider: head as ProviderName, model: spec.slice(slash + 1) };
    }
  }
  return { provider: "anthropic", model: spec };
}

interface OpenAICompatConfig {
  baseURL: string;
  apiKeyEnv: string[]; // first non-empty wins
  keyless: boolean; // ollama
}

function ollamaBaseUrl(): string {
  const cfg = inheritedConfig();
  const raw = typeof cfg["OllamaBaseUrl"] === "string" ? (cfg["OllamaBaseUrl"] as string) : "";
  const base = (raw || "http://localhost:11434").replace(/\/+$/, "");
  return `${base}/v1`;
}

function openAICompatConfig(provider: ProviderName): OpenAICompatConfig {
  switch (provider) {
    case "openai":
      return { baseURL: "https://api.openai.com/v1", apiKeyEnv: ["OPENAI_API_KEY"], keyless: false };
    case "deepseek":
      return { baseURL: "https://api.deepseek.com", apiKeyEnv: ["DEEPSEEK_API_KEY"], keyless: false };
    case "gemini":
      return {
        baseURL: "https://generativelanguage.googleapis.com/v1beta/openai/",
        apiKeyEnv: ["GEMINI_API_KEY", "GOOGLE_API_KEY"],
        keyless: false,
      };
    case "ollama":
      return { baseURL: ollamaBaseUrl(), apiKeyEnv: [], keyless: true };
    default:
      throw new Error(`Provider '${provider}' is not OpenAI-compatible.`);
  }
}

function envKey(names: string[]): string {
  for (const n of names) {
    const v = process.env[n];
    if (v) return v;
  }
  return "";
}

// ---------------------------------------------------------------------------
// Clients (lazily created, cached per provider)
// ---------------------------------------------------------------------------

let _anthropic: Anthropic | null = null;

function anthropicClient(): Anthropic {
  if (!_anthropic) {
    const apiKey = process.env["ANTHROPIC_API_KEY"] ?? "";
    if (!apiKey) {
      throw new Error("ANTHROPIC_API_KEY not set. Add it to .env or your environment.");
    }
    _anthropic = new Anthropic({ apiKey });
  }
  return _anthropic;
}

const _openaiClients = new Map<ProviderName, OpenAI>();

function openAIClient(provider: ProviderName): OpenAI {
  const existing = _openaiClients.get(provider);
  if (existing) return existing;
  const cfg = openAICompatConfig(provider);
  const apiKey = cfg.keyless ? "ollama" : envKey(cfg.apiKeyEnv);
  if (!apiKey && !cfg.keyless) {
    throw new Error(
      `No API key for provider '${provider}'. Set one of: ${cfg.apiKeyEnv.join(", ")} in .env.`,
    );
  }
  const client = new OpenAI({ apiKey: apiKey || "ollama", baseURL: cfg.baseURL });
  _openaiClients.set(provider, client);
  return client;
}

// ---------------------------------------------------------------------------
// Usage + cost
// ---------------------------------------------------------------------------

export interface Usage {
  inputTokens: number;
  outputTokens: number;
  cacheCreationInputTokens: number;
  cacheReadInputTokens: number;
  provider: string;
  model: string;
}

export function emptyUsage(): Usage {
  return {
    inputTokens: 0,
    outputTokens: 0,
    cacheCreationInputTokens: 0,
    cacheReadInputTokens: 0,
    provider: "",
    model: "",
  };
}

export function addUsage(a: Usage, b: Usage): Usage {
  return {
    inputTokens: a.inputTokens + b.inputTokens,
    outputTokens: a.outputTokens + b.outputTokens,
    cacheCreationInputTokens: a.cacheCreationInputTokens + b.cacheCreationInputTokens,
    cacheReadInputTokens: a.cacheReadInputTokens + b.cacheReadInputTokens,
    provider: a.provider || b.provider,
    model: a.model || b.model,
  };
}

interface PriceRow {
  input: number;
  output: number;
  cache_read: number;
  cache_create: number;
}

/** Look up per-MTok pricing for "provider/model" in the inherited config. */
function pricingFor(provider: string, model: string): PriceRow | null {
  const pricing = inheritedConfig()["Pricing"];
  if (!pricing || typeof pricing !== "object") return null;
  const row = (pricing as Record<string, unknown>)[`${provider}/${model}`];
  if (!row || typeof row !== "object") return null;
  const r = row as Record<string, unknown>;
  const num = (v: unknown): number => (typeof v === "number" ? v : 0);
  return {
    input: num(r["input"]),
    output: num(r["output"]),
    cache_read: num(r["cache_read"]),
    cache_create: num(r["cache_create"]),
  };
}

/**
 * Estimate USD cost from a Usage record using the agent's Pricing config.
 * Returns 0 when the provider/model pair has no pricing entry (e.g. local
 * Ollama models, or a model id not yet listed in config Pricing).
 */
export function estimateCost(usage: Usage): number {
  const row = pricingFor(usage.provider, usage.model);
  if (!row) return 0;
  return (
    (usage.inputTokens * row.input +
      usage.outputTokens * row.output +
      usage.cacheCreationInputTokens * row.cache_create +
      usage.cacheReadInputTokens * row.cache_read) /
    1_000_000
  );
}

// ---------------------------------------------------------------------------
// Message creation
// ---------------------------------------------------------------------------

async function anthropicCreate(
  model: string,
  maxTokens: number,
  messages: ChatMessage[],
  options?: { system?: string; temperature?: number },
): Promise<[string, Usage]> {
  const client = anthropicClient();
  const params: Anthropic.MessageCreateParams = {
    model,
    max_tokens: maxTokens,
    temperature: options?.temperature ?? 1.0,
    messages: messages.map((m) => ({ role: m.role, content: m.content })),
  };
  if (options?.system) {
    params.system = options.system;
  }
  const response = await client.messages.create(params);
  const text = response.content[0]?.type === "text" ? response.content[0].text : "";
  const raw = response.usage as unknown as Record<string, number>;
  const usage: Usage = {
    inputTokens: response.usage.input_tokens,
    outputTokens: response.usage.output_tokens,
    cacheCreationInputTokens: raw["cache_creation_input_tokens"] ?? 0,
    cacheReadInputTokens: raw["cache_read_input_tokens"] ?? 0,
    provider: "anthropic",
    model: response.model || model,
  };
  return [text, usage];
}

function toOpenAIMessages(
  messages: ChatMessage[],
  system?: string,
): OpenAI.Chat.ChatCompletionMessageParam[] {
  const out: OpenAI.Chat.ChatCompletionMessageParam[] = [];
  if (system) {
    out.push({ role: "system", content: system });
  }
  for (const m of messages) {
    out.push({ role: m.role, content: m.content });
  }
  return out;
}

function openAIUsage(
  provider: ProviderName,
  model: string,
  raw: OpenAI.CompletionUsage | undefined,
): Usage {
  const cached = raw?.prompt_tokens_details?.cached_tokens ?? 0;
  return {
    inputTokens: raw?.prompt_tokens ?? 0,
    outputTokens: raw?.completion_tokens ?? 0,
    cacheCreationInputTokens: 0,
    cacheReadInputTokens: cached,
    provider,
    model,
  };
}

async function openAICreate(
  provider: ProviderName,
  model: string,
  maxTokens: number,
  messages: ChatMessage[],
  options?: { system?: string; temperature?: number },
): Promise<[string, Usage]> {
  const client = openAIClient(provider);
  const response = await client.chat.completions.create({
    model,
    max_tokens: maxTokens,
    temperature: options?.temperature ?? 1.0,
    messages: toOpenAIMessages(messages, options?.system),
  });
  const text = response.choices[0]?.message?.content ?? "";
  return [text, openAIUsage(provider, response.model || model, response.usage)];
}

/**
 * Non-streaming message creation. `spec` selects provider + model (see file
 * header). Returns [text, usage]. Usage is folded into the run-wide accumulator
 * for the __USAGE__ report.
 */
export async function createMessage(
  spec: string | ModelSpec,
  maxTokens: number,
  messages: ChatMessage[],
  options?: { system?: string; temperature?: number },
): Promise<[string, Usage]> {
  const { provider, model } = resolveSpec(spec);
  const result =
    provider === "anthropic"
      ? await anthropicCreate(model, maxTokens, messages, options)
      : await openAICreate(provider, model, maxTokens, messages, options);
  recordUsage(result[1]);
  return result;
}

async function anthropicStream(
  model: string,
  maxTokens: number,
  messages: ChatMessage[],
  options?: { system?: string; temperature?: number },
): Promise<[string, Usage]> {
  const client = anthropicClient();
  const params: Anthropic.MessageCreateParams = {
    model,
    max_tokens: maxTokens,
    temperature: options?.temperature ?? 1.0,
    messages: messages.map((m) => ({ role: m.role, content: m.content })),
  };
  if (options?.system) {
    params.system = options.system;
  }
  const stream = client.messages.stream(params);
  stream.on("text", (text) => process.stdout.write(text));
  const response = await stream.finalMessage();
  const text = response.content[0]?.type === "text" ? response.content[0].text : "";
  const raw = response.usage as unknown as Record<string, number>;
  const usage: Usage = {
    inputTokens: response.usage.input_tokens,
    outputTokens: response.usage.output_tokens,
    cacheCreationInputTokens: raw["cache_creation_input_tokens"] ?? 0,
    cacheReadInputTokens: raw["cache_read_input_tokens"] ?? 0,
    provider: "anthropic",
    model: response.model || model,
  };
  return [text, usage];
}

async function openAIStream(
  provider: ProviderName,
  model: string,
  maxTokens: number,
  messages: ChatMessage[],
  options?: { system?: string; temperature?: number },
): Promise<[string, Usage]> {
  const client = openAIClient(provider);
  const stream = await client.chat.completions.create({
    model,
    max_tokens: maxTokens,
    temperature: options?.temperature ?? 1.0,
    messages: toOpenAIMessages(messages, options?.system),
    stream: true,
    stream_options: { include_usage: true },
  });
  let text = "";
  let usageRaw: OpenAI.CompletionUsage | undefined;
  let resolvedModel = model;
  for await (const chunk of stream) {
    if (chunk.model) resolvedModel = chunk.model;
    const delta = chunk.choices[0]?.delta?.content;
    if (delta) {
      process.stdout.write(delta);
      text += delta;
    }
    if (chunk.usage) usageRaw = chunk.usage;
  }
  return [text, openAIUsage(provider, resolvedModel, usageRaw)];
}

/**
 * Streaming message creation — prints text deltas to stdout in real time.
 * Note: only safe in standalone (--run) mode; in MCP server mode stdout is the
 * transport. `spec` selects provider + model. Returns [text, usage].
 */
export async function streamMessage(
  spec: string | ModelSpec,
  maxTokens: number,
  messages: ChatMessage[],
  options?: { system?: string; temperature?: number },
): Promise<[string, Usage]> {
  const { provider, model } = resolveSpec(spec);
  const result =
    provider === "anthropic"
      ? await anthropicStream(model, maxTokens, messages, options)
      : await openAIStream(provider, model, maxTokens, messages, options);
  recordUsage(result[1]);
  return result;
}

// ---------------------------------------------------------------------------
// Module-level usage accumulator. Every createMessage / streamMessage call is
// folded in automatically. On subprocess exit (beforeExit), if any LLM calls
// were made, a `__USAGE__:` sentinel line is written to stderr. codegen
// run_task parses this and surfaces it in its CallToolResult.
//
// Per-task code does not need to opt in — importing createMessage is enough.
// ---------------------------------------------------------------------------

let _accumulator: Usage = emptyUsage();
let _callCount = 0;

function recordUsage(usage: Usage): void {
  _accumulator = addUsage(_accumulator, usage);
  _callCount++;
}

interface UsageReport {
  input_tokens: number;
  output_tokens: number;
  cache_read_input_tokens: number;
  cache_creation_input_tokens: number;
  provider: string;
  model: string;
  cost_usd: number;
  calls: number;
}

function buildUsageReport(): UsageReport | null {
  if (_callCount === 0) return null;
  return {
    input_tokens: _accumulator.inputTokens,
    output_tokens: _accumulator.outputTokens,
    cache_read_input_tokens: _accumulator.cacheReadInputTokens,
    cache_creation_input_tokens: _accumulator.cacheCreationInputTokens,
    provider: _accumulator.provider,
    model: _accumulator.model,
    cost_usd: estimateCost(_accumulator),
    calls: _callCount,
  };
}

let _exitHandlerWritten = false;
process.on("beforeExit", () => {
  if (_exitHandlerWritten) return;
  const report = buildUsageReport();
  if (!report) return;
  process.stderr.write("__USAGE__:" + JSON.stringify(report) + "\n");
  _exitHandlerWritten = true;
});
