/**
 * Generic LLM helper for Anthropic Claude API.
 *
 * Provides non-streaming and streaming message creation with cost tracking.
 * Reads ANTHROPIC_API_KEY from environment. Client is created lazily on first use.
 *
 * DO NOT EDIT THIS FILE.
 */

import Anthropic from "@anthropic-ai/sdk";

// Per-token pricing (USD). Format: [input_per_M, output_per_M, cache_write_per_M, cache_read_per_M]
const PRICING: Record<string, [number, number, number, number]> = {
  "claude-opus":   [15.0, 75.0, 18.75, 1.50],
  "claude-sonnet": [3.0,  15.0, 3.75,  0.30],
  "claude-haiku":  [0.80, 4.0,  1.0,   0.08],
};

export interface Usage {
  inputTokens: number;
  outputTokens: number;
  cacheCreationInputTokens: number;
  cacheReadInputTokens: number;
  model: string;
}

export function emptyUsage(): Usage {
  return { inputTokens: 0, outputTokens: 0, cacheCreationInputTokens: 0, cacheReadInputTokens: 0, model: "" };
}

export function addUsage(a: Usage, b: Usage): Usage {
  return {
    inputTokens: a.inputTokens + b.inputTokens,
    outputTokens: a.outputTokens + b.outputTokens,
    cacheCreationInputTokens: a.cacheCreationInputTokens + b.cacheCreationInputTokens,
    cacheReadInputTokens: a.cacheReadInputTokens + b.cacheReadInputTokens,
    model: a.model || b.model,
  };
}

export function estimateCost(usage: Usage): number {
  for (const [prefix, [inp, out, cw, cr]] of Object.entries(PRICING)) {
    if (usage.model.startsWith(prefix)) {
      return (
        usage.inputTokens * inp +
        usage.outputTokens * out +
        usage.cacheCreationInputTokens * cw +
        usage.cacheReadInputTokens * cr
      ) / 1_000_000;
    }
  }
  return 0;
}

let _client: Anthropic | null = null;

function getClient(): Anthropic {
  if (!_client) {
    const apiKey = process.env["ANTHROPIC_API_KEY"] ?? "";
    if (!apiKey) {
      throw new Error("ANTHROPIC_API_KEY not set. Add it to .env or set it in your environment.");
    }
    _client = new Anthropic({ apiKey });
  }
  return _client;
}

function extractUsage(response: Anthropic.Message, model: string): Usage {
  const raw = response.usage;
  return {
    inputTokens: raw.input_tokens,
    outputTokens: raw.output_tokens,
    cacheCreationInputTokens: (raw as unknown as Record<string, number>)["cache_creation_input_tokens"] ?? 0,
    cacheReadInputTokens: (raw as unknown as Record<string, number>)["cache_read_input_tokens"] ?? 0,
    model,
  };
}

export async function createMessage(
  model: string,
  maxTokens: number,
  messages: Anthropic.MessageParam[],
  options?: { system?: string; temperature?: number },
): Promise<[string, Usage]> {
  const client = getClient();
  const params: Anthropic.MessageCreateParams = {
    model,
    max_tokens: maxTokens,
    temperature: options?.temperature ?? 1.0,
    messages,
  };
  if (options?.system) {
    params.system = options.system;
  }
  const response = await client.messages.create(params);
  const text = response.content[0]?.type === "text" ? response.content[0].text : "";
  const usage = extractUsage(response, model);
  recordUsage(usage);
  return [text, usage];
}

export async function streamMessage(
  model: string,
  maxTokens: number,
  messages: Anthropic.MessageParam[],
  options?: { system?: string; temperature?: number },
): Promise<[string, Usage]> {
  const client = getClient();
  const params: Anthropic.MessageCreateParams = {
    model,
    max_tokens: maxTokens,
    temperature: options?.temperature ?? 1.0,
    messages,
  };
  if (options?.system) {
    params.system = options.system;
  }
  const stream = client.messages.stream(params);
  stream.on("text", (text) => process.stdout.write(text));
  const response = await stream.finalMessage();
  const text = response.content[0]?.type === "text" ? response.content[0].text : "";
  const usage = extractUsage(response, model);
  recordUsage(usage);
  return [text, usage];
}

// ---------------------------------------------------------------------------
// Module-level usage accumulator. Every createMessage / streamMessage call is
// folded in automatically. On subprocess exit (beforeExit), if any LLM calls
// were made, a `__USAGE__:` sentinel line is written to stderr. codegen
// run_task parses this and surfaces it in its CallToolResult.
//
// Per-task code does not need to opt in — importing createMessage is enough.
// ---------------------------------------------------------------------------

let _accumulator: Usage = emptyUsage();
let _callCount = 0;

function recordUsage(usage: Usage): void {
  _accumulator = addUsage(_accumulator, usage);
  _callCount++;
}

interface UsageReport {
  input_tokens: number;
  output_tokens: number;
  cache_read_input_tokens: number;
  cache_creation_input_tokens: number;
  model: string;
  cost_usd: number;
  calls: number;
}

function buildUsageReport(): UsageReport | null {
  if (_callCount === 0) return null;
  return {
    input_tokens: _accumulator.inputTokens,
    output_tokens: _accumulator.outputTokens,
    cache_read_input_tokens: _accumulator.cacheReadInputTokens,
    cache_creation_input_tokens: _accumulator.cacheCreationInputTokens,
    model: _accumulator.model,
    cost_usd: estimateCost(_accumulator),
    calls: _callCount,
  };
}

let _exitHandlerWritten = false;
process.on("beforeExit", () => {
  if (_exitHandlerWritten) return;
  const report = buildUsageReport();
  if (!report) return;
  process.stderr.write("__USAGE__:" + JSON.stringify(report) + "\n");
  _exitHandlerWritten = true;
});
