/**
 * Lightweight MCP stdio client for connecting to MCP servers and calling tools.
 *
 * Usage:
 *   const client = new McpClient("my-server");
 *   await client.connect("node", ["server.js"]);
 *   const tools = await client.listTools();
 *   const result = await client.callTool("tool_name", { arg: "value" });
 *   await client.close();
 *
 * DO NOT EDIT THIS FILE.
 */

import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";

const SHUTDOWN_TIMEOUT_MS = 5000;
const MAX_RETRIES = 3;
const RETRY_BASE_MS = 1000;

/** Errors worth retrying (transport-level failures). */
function isTransientError(err: unknown): boolean {
  if (err instanceof Error) {
    const msg = err.message.toLowerCase();
    return msg.includes("broken pipe") ||
           msg.includes("econnreset") ||
           msg.includes("epipe") ||
           msg.includes("timeout") ||
           msg.includes("econnrefused");
  }
  return false;
}

export class McpClient {
  readonly name: string;
  private client: Client | null = null;
  private transport: StdioClientTransport | null = null;

  constructor(name: string) {
    this.name = name;
  }

  async connect(
    command: string,
    args: string[],
    env?: Record<string, string>,
  ): Promise<void> {
    const mergedEnv = { ...process.env, ...env } as Record<string, string>;

    this.transport = new StdioClientTransport({
      command,
      args,
      env: mergedEnv,
    });

    this.client = new Client(
      { name: `task-client-${this.name}`, version: "0.1.0" },
      { capabilities: {} },
    );

    await this.client.connect(this.transport);
  }

  async listTools(): Promise<Array<{ name: string; description: string }>> {
    if (!this.client) {
      throw new Error(`MCP client '${this.name}' not connected`);
    }
    const result = await this.client.listTools();
    return result.tools.map((t) => ({
      name: t.name,
      description: t.description ?? "",
    }));
  }

  async callTool(
    name: string,
    args?: Record<string, unknown>,
  ): Promise<unknown> {
    if (!this.client) {
      throw new Error(`MCP client '${this.name}' not connected`);
    }

    let lastError: unknown;
    for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) {
      try {
        const result = await this.client.callTool({
          name,
          arguments: args ?? {},
        });

        // Check for tool errors before returning data
        if (result.isError) {
          const parts: string[] = [];
          for (const block of result.content as Array<{ type: string; text?: string }>) {
            if (block.text) parts.push(block.text);
          }
          const errorText = parts.join("\n") || "Unknown tool error";
          throw new Error(
            `MCP tool '${name}' on '${this.name}' failed: ${errorText}`,
          );
        }

        // Prefer structuredContent (JSON) over text content
        if (result.structuredContent != null) {
          return result.structuredContent;
        }

        // Fall back to text content
        const textParts: string[] = [];
        for (const block of result.content as Array<{ type: string; text?: string }>) {
          if (block.text) textParts.push(block.text);
        }
        return textParts.join("\n") || "";
      } catch (err) {
        lastError = err;
        // Don't retry application-level errors (tool said "this failed")
        if (err instanceof Error && err.message.includes("MCP tool '")) {
          throw err;
        }
        if (!isTransientError(err) || attempt === MAX_RETRIES) {
          throw err;
        }
        const delay = RETRY_BASE_MS * Math.pow(2, attempt - 1);
        console.warn(
          `  ${this.name}: ${name} attempt ${attempt} failed, retrying in ${delay}ms...`,
        );
        await new Promise((r) => setTimeout(r, delay));
      }
    }
    throw lastError;
  }

  async close(): Promise<void> {
    if (!this.transport) return;
    try {
      await Promise.race([
        this.transport.close(),
        new Promise((_, reject) =>
          setTimeout(() => reject(new Error("shutdown timeout")), SHUTDOWN_TIMEOUT_MS),
        ),
      ]);
    } catch {
      // Swallow shutdown errors
    }
    this.client = null;
    this.transport = null;
  }
}
