/**
 * Shared type for multi-tool codegen task apps — DO NOT EDIT THIS FILE.
 *
 * A task app can export `TOOLS: ToolDef[]` from `task.ts` to expose multiple
 * related MCP tools from one server. See PLAN-codegen-multi-tool.md.
 */

import type { McpClient } from "./mcp-client.js";

export type Clients = Record<string, McpClient>;

// inputSchema is intentionally typed as unknown: the field always holds a
// Zod raw shape ({ [key]: zodType }), but zod 3.25's preview $ZodType types
// don't unify cleanly with the MCP SDK's older ZodRawShape signature. The
// runtime accepts both; the template casts at the SDK boundary.
export interface ToolDef {
  name: string;
  description: string;
  inputSchema: unknown;
  handler: (
    input: Record<string, unknown>,
    clients: Clients,
    profile: Record<string, unknown>,
    config: Record<string, unknown>,
  ) => Promise<Record<string, unknown>>;
}

// Identity helper. Lets callers write `defineTools([...])` symmetrically with
// other "define" helpers without TypeScript complaining about the return type.
export function defineTools(tools: ToolDef[]): ToolDef[] {
  return tools;
}
