/**
 * Shared utilities — DO NOT EDIT THIS FILE.
 */

import { mkdir, writeFile as fsWriteFile, appendFile as fsAppendFile } from "node:fs/promises";
import { resolve, dirname, isAbsolute } from "node:path";

export function getOutputDir(config: Record<string, unknown>): string {
  const wd = config["WorkingDirectory"];
  if (typeof wd === "string" && wd) {
    return resolve(wd);
  }
  return process.cwd();
}

function resolvePath(path: string, config?: Record<string, unknown>): string {
  if (isAbsolute(path)) return path;
  if (config) {
    return resolve(getOutputDir(config), path);
  }
  return resolve(path);
}

export async function writeFile(
  path: string,
  content: string,
  config?: Record<string, unknown>,
): Promise<string> {
  const resolved = resolvePath(path, config);
  await mkdir(dirname(resolved), { recursive: true });
  await fsWriteFile(resolved, content, "utf-8");
  return resolved;
}

export async function appendFile(
  path: string,
  content: string,
  config?: Record<string, unknown>,
): Promise<string> {
  const resolved = resolvePath(path, config);
  await mkdir(dirname(resolved), { recursive: true });
  await fsAppendFile(resolved, content, "utf-8");
  return resolved;
}
