/**
 * NativeClient — an in-process {@link IMcpClient} backed by the native tool
 * implementations in this folder (filesystem.ts, system-info.ts) instead of a
 * subprocess MCP server.
 *
 * These capabilities are NATIVE in the agent (in-process Python Tool objects,
 * not MCP servers — see ADR-025 / native_tools/). A codegen task is a separate
 * Node process and can't reach those objects, so it gets its own in-process
 * implementation here. The typed wrappers in tools.ts (fsBash, fsRead, …) call
 * `client.callTool(...)` and don't care whether the client is an MCP subprocess
 * or this shim, so generated task code is unchanged.
 *
 * DO NOT EDIT THIS FILE.
 */

import type { IMcpClient } from "../mcp-client.js";
import { callFilesystemTool, FILESYSTEM_TOOL_NAMES, type FsConfig } from "./filesystem.js";
import { loadPathPolicy } from "./paths.js";
import { callSystemInfoTool, SYSTEM_INFO_TOOL_NAMES } from "./system-info.js";

/** Server names served in-process rather than spawned as MCP subprocesses. */
export const NATIVE_SERVERS = ["filesystem", "system-info"] as const;
export type NativeServerName = (typeof NATIVE_SERVERS)[number];

export function isNativeServer(name: string): name is NativeServerName {
  return (NATIVE_SERVERS as readonly string[]).includes(name);
}

const DEFAULT_MEMORY_MAX_LINES = 200;

class NativeClient implements IMcpClient {
  readonly name: string;
  private readonly dispatch: (tool: string, args: Record<string, unknown>) => Promise<unknown>;
  private readonly toolNames: readonly string[];

  constructor(
    name: string,
    toolNames: readonly string[],
    dispatch: (tool: string, args: Record<string, unknown>) => Promise<unknown>,
  ) {
    this.name = name;
    this.toolNames = toolNames;
    this.dispatch = dispatch;
  }

  async listTools(): Promise<Array<{ name: string; description: string }>> {
    return this.toolNames.map((name) => ({ name, description: "" }));
  }

  async callTool(name: string, args?: Record<string, unknown>): Promise<unknown> {
    try {
      return await this.dispatch(name, args ?? {});
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      throw new Error(`MCP tool '${name}' on '${this.name}' failed: ${message}`);
    }
  }

  async close(): Promise<void> {
    // Nothing to tear down — no subprocess, no transport.
  }
}

/** Read the FsConfig from a task's loaded config (the top-level `Filesystem` block). */
function fsConfigFrom(config: Record<string, unknown>): FsConfig {
  const fsCfg = (config["Filesystem"] ?? {}) as Record<string, unknown>;
  const workingDir =
    typeof fsCfg["WorkingDir"] === "string" && fsCfg["WorkingDir"]
      ? (fsCfg["WorkingDir"] as string)
      : process.cwd();
  const allowed = typeof fsCfg["AllowedDirs"] === "string" ? (fsCfg["AllowedDirs"] as string) : undefined;
  const readonly = typeof fsCfg["ReadonlyDirs"] === "string" ? (fsCfg["ReadonlyDirs"] as string) : undefined;
  const memoryDir = typeof fsCfg["MemoryDir"] === "string" ? (fsCfg["MemoryDir"] as string) : undefined;
  const maxLinesRaw = fsCfg["MemoryMaxLines"];
  const memoryMaxLines =
    typeof maxLinesRaw === "number" && Number.isFinite(maxLinesRaw)
      ? maxLinesRaw
      : DEFAULT_MEMORY_MAX_LINES;

  return {
    policy: loadPathPolicy(workingDir, allowed, readonly),
    workingDir,
    memoryDir,
    memoryMaxLines,
  };
}

/**
 * Build the in-process client for a native server, or return null if `name`
 * is not a native server (caller should fall back to spawning an MCP server).
 */
export function createNativeClient(
  name: string,
  config: Record<string, unknown>,
): IMcpClient | null {
  if (name === "filesystem") {
    const fsConfig = fsConfigFrom(config);
    return new NativeClient("filesystem", FILESYSTEM_TOOL_NAMES, (tool, args) =>
      callFilesystemTool(fsConfig, tool, args),
    );
  }
  if (name === "system-info") {
    return new NativeClient("system-info", SYSTEM_INFO_TOOL_NAMES, (tool) =>
      callSystemInfoTool(tool),
    );
  }
  return null;
}
