/**
 * Native (in-process) filesystem tools for codegen tasks.
 *
 * Faithful port of the per-tool logic in
 * mcp_servers/ts/packages/filesystem/src/tools/*.ts, minus the MCP
 * server/logging shell. Each function returns the same structuredContent
 * shape the MCP filesystem server returns, or THROWS on error (the
 * NativeClient turns a throw into the same error a real MCP tool failure
 * would surface, so the typed wrappers in tools.ts behave identically
 * whether a task is backed by the native tools or an MCP subprocess).
 *
 * DO NOT EDIT THIS FILE — keep it in sync with the filesystem MCP package.
 */

import { execFile } from "node:child_process";
import { existsSync } from "node:fs";
import {
  access,
  appendFile,
  mkdir,
  open,
  readFile,
  rename,
  stat,
  unlink,
  writeFile,
} from "node:fs/promises";
import { randomUUID } from "node:crypto";
import path from "node:path";

import fg from "fast-glob";
import { rgPath } from "@vscode/ripgrep";

import {
  isPathAllowed,
  requireWritable,
  resolveAllowed,
  type PathPolicy,
} from "./paths.js";

const IS_WINDOWS = process.platform === "win32";
const BINARY_SNIFF_BYTES = 8 * 1024;
const TIMEOUT_MS = 30_000;
const MAX_BUFFER = 10 * 1024 * 1024;

export interface FsConfig {
  policy: PathPolicy;
  workingDir: string;
  memoryDir?: string;
  memoryMaxLines: number;
}

// ---------------------------------------------------------------------------
// read_file
// ---------------------------------------------------------------------------

const READ_DEFAULT_LIMIT = 2000;
const READ_LINE_NUM_WIDTH = 6;

export async function readFileTool(
  cfg: FsConfig,
  input: { path: string; offset?: number; limit?: number },
): Promise<Record<string, unknown>> {
  const offset = input.offset ?? 1;
  const limit = input.limit ?? READ_DEFAULT_LIMIT;
  const resolvedPath = await resolveAllowed(cfg.policy, input.path, { mustExist: true });

  let rawText: string;
  if (resolvedPath.toLowerCase().endsWith(".docx")) {
    rawText = await readDocx(resolvedPath);
  } else {
    const buf = await readFile(resolvedPath);
    if (isBinary(buf)) {
      throw new Error(
        `refusing to read binary file: ${resolvedPath} (null byte detected in first ${BINARY_SNIFF_BYTES} bytes)`,
      );
    }
    rawText = buf.toString("utf-8");
  }

  const allLines = splitLines(rawText);
  const totalLines = allLines.length;
  const sizeBytes = Buffer.byteLength(rawText, "utf-8");

  const startIndex = offset - 1;
  const endIndex = Math.min(startIndex + limit, totalLines);
  const slicedLines = startIndex < totalLines ? allLines.slice(startIndex, endIndex) : [];
  const startLine = slicedLines.length > 0 ? offset : 0;
  const endLine = slicedLines.length > 0 ? offset + slicedLines.length - 1 : 0;
  const truncated = endIndex < totalLines;

  let formatted: string;
  if (totalLines === 0) {
    formatted = "(file is empty)";
  } else if (slicedLines.length === 0) {
    formatted = `(offset ${offset} is past end of file — file has ${totalLines} lines)`;
  } else {
    const formattedLines = slicedLines.map((line, i) => {
      const lineNum = String(offset + i).padStart(READ_LINE_NUM_WIDTH, " ");
      return `${lineNum}\t${line}`;
    });
    formatted = formattedLines.join("\n");
    if (truncated) {
      const shownBytes = Buffer.byteLength(slicedLines.join("\n"), "utf-8");
      const linePct = Math.max(1, Math.round((slicedLines.length / totalLines) * 100));
      const nextOffset = endLine + 1;
      formatted +=
        `\n\n[Output truncated: showed lines ${startLine}-${endLine} of ${totalLines} ` +
        `(${linePct}%, ${formatBytes(shownBytes)} of ${formatBytes(sizeBytes)}).\n` +
        ` To read more: read_file(path="${resolvedPath}", offset=${nextOffset}, limit=${limit})]`;
    }
  }

  return {
    content: formatted,
    path: resolvedPath,
    size_bytes: sizeBytes,
    total_lines: totalLines,
    start_line: startLine,
    end_line: endLine,
    truncated,
  };
}

async function readDocx(filePath: string): Promise<string> {
  const mammoth = await import("mammoth");
  const result = await mammoth.default.extractRawText({ path: filePath });
  return result.value;
}

// ---------------------------------------------------------------------------
// write_file
// ---------------------------------------------------------------------------

export async function writeFileTool(
  cfg: FsConfig,
  input: { path: string; content: string },
): Promise<Record<string, unknown>> {
  const resolvedPath = await resolveAllowed(cfg.policy, input.path, { mustExist: false });
  await requireWritable(cfg.policy, resolvedPath);

  await mkdir(path.dirname(resolvedPath), { recursive: true });
  await writeFile(resolvedPath, input.content, "utf-8");

  return {
    success: true,
    path: resolvedPath,
    size_bytes: Buffer.byteLength(input.content, "utf-8"),
  };
}

// ---------------------------------------------------------------------------
// append_file
// ---------------------------------------------------------------------------

export async function appendFileTool(
  cfg: FsConfig,
  input: { path: string; content: string },
): Promise<Record<string, unknown>> {
  const resolvedPath = await resolveAllowed(cfg.policy, input.path, { mustExist: false });
  await requireWritable(cfg.policy, resolvedPath);

  try {
    await access(resolvedPath);
  } catch {
    throw new Error(`file does not exist: ${resolvedPath}. Use write_file to create it first.`);
  }

  await appendFile(resolvedPath, input.content, "utf-8");

  return {
    success: true,
    path: resolvedPath,
    appended_bytes: Buffer.byteLength(input.content, "utf-8"),
  };
}

// ---------------------------------------------------------------------------
// delete_file
// ---------------------------------------------------------------------------

export async function deleteFileTool(
  cfg: FsConfig,
  input: { path: string },
): Promise<Record<string, unknown>> {
  const resolvedPath = await resolveAllowed(cfg.policy, input.path, { mustExist: false });
  await requireWritable(cfg.policy, resolvedPath);

  let st;
  try {
    st = await stat(resolvedPath);
  } catch {
    throw new Error(`file not found: ${resolvedPath}`);
  }
  if (st.isDirectory()) {
    throw new Error(
      `refusing to delete directory: ${resolvedPath} — use bash (rm -r / rmdir) for directory removal`,
    );
  }
  if (!st.isFile()) {
    throw new Error(`not a regular file: ${resolvedPath}`);
  }

  await unlink(resolvedPath);
  return { path: resolvedPath, deleted: true, size_bytes: st.size };
}

// ---------------------------------------------------------------------------
// edit_file
// ---------------------------------------------------------------------------

const EDIT_MAX_BYTES = 5 * 1024 * 1024;
const EOL_SAMPLE_BYTES = 64 * 1024;
const BOM = Buffer.from([0xef, 0xbb, 0xbf]);

export async function editFileTool(
  cfg: FsConfig,
  input: { path: string; old_string: string; new_string: string; replace_all?: boolean },
): Promise<Record<string, unknown>> {
  const replaceAll = input.replace_all ?? false;

  if (input.old_string.length === 0) {
    throw new Error("old_string is empty — provide the exact text to replace");
  }
  if (input.old_string === input.new_string) {
    throw new Error("old_string and new_string are identical — refusing no-op");
  }

  const resolvedPath = await resolveAllowed(cfg.policy, input.path, { mustExist: false });
  await requireWritable(cfg.policy, resolvedPath);

  let st;
  try {
    st = await stat(resolvedPath);
  } catch {
    throw new Error(`file not found: ${resolvedPath}`);
  }
  if (!st.isFile()) {
    throw new Error(`not a regular file: ${resolvedPath}`);
  }
  if (st.size > EDIT_MAX_BYTES) {
    throw new Error(
      `file too large for edit_file (${st.size} bytes > ${EDIT_MAX_BYTES}) — use write_file or split the edit`,
    );
  }

  const buf = await readFile(resolvedPath);
  if (isBinary(buf)) {
    throw new Error(
      `refusing to edit binary file: ${resolvedPath} (null byte detected in first ${BINARY_SNIFF_BYTES} bytes)`,
    );
  }

  const hasBOM = buf.length >= 3 && buf[0] === 0xef && buf[1] === 0xbb && buf[2] === 0xbf;
  const text = buf.toString("utf-8", hasBOM ? 3 : 0);

  const eol = detectEOL(text);
  const oldNorm = normaliseEOL(input.old_string, eol);
  const newNorm = normaliseEOL(input.new_string, eol);

  const count = countOccurrences(text, oldNorm);
  if (count === 0) {
    throw new Error(`old_string not found in ${resolvedPath}`);
  }
  if (count > 1 && !replaceAll) {
    throw new Error(
      `old_string is not unique (${count} matches) in ${resolvedPath} — add surrounding context or set replace_all=true`,
    );
  }

  let updated: string;
  let replacements: number;
  if (replaceAll) {
    updated = text.split(oldNorm).join(newNorm);
    replacements = count;
  } else {
    const idx = text.indexOf(oldNorm);
    updated = text.slice(0, idx) + newNorm + text.slice(idx + oldNorm.length);
    replacements = 1;
  }

  const updatedBuf = hasBOM
    ? Buffer.concat([BOM, Buffer.from(updated, "utf-8")])
    : Buffer.from(updated, "utf-8");

  await atomicWrite(resolvedPath, updatedBuf, st.mode);

  return { path: resolvedPath, replacements };
}

function detectEOL(text: string): "\r\n" | "\n" {
  const sample = text.length > EOL_SAMPLE_BYTES ? text.slice(0, EOL_SAMPLE_BYTES) : text;
  return sample.includes("\r\n") ? "\r\n" : "\n";
}

function normaliseEOL(s: string, target: "\r\n" | "\n"): string {
  const lf = s.replace(/\r\n/g, "\n").replace(/\r/g, "\n");
  return target === "\n" ? lf : lf.replace(/\n/g, "\r\n");
}

function countOccurrences(haystack: string, needle: string): number {
  if (needle.length === 0) return 0;
  let count = 0;
  let pos = 0;
  while (true) {
    const found = haystack.indexOf(needle, pos);
    if (found === -1) return count;
    count++;
    pos = found + needle.length;
  }
}

async function atomicWrite(filePath: string, content: Buffer, mode: number): Promise<void> {
  const dir = path.dirname(filePath);
  const base = path.basename(filePath);
  const tempPath = path.join(dir, `.${base}.${randomUUID()}.tmp`);

  const handle = await open(tempPath, "w", mode & 0o777);
  try {
    await handle.writeFile(content);
    await handle.sync();
  } finally {
    await handle.close();
  }
  await rename(tempPath, filePath);
}

// ---------------------------------------------------------------------------
// glob
// ---------------------------------------------------------------------------

const GLOB_DEFAULT_HEAD_LIMIT = 250;

export async function globTool(
  cfg: FsConfig,
  input: { pattern: string; path?: string; head_limit?: number },
): Promise<Record<string, unknown>> {
  const headLimit = input.head_limit ?? GLOB_DEFAULT_HEAD_LIMIT;
  const root = await resolveAllowed(cfg.policy, input.path, { mustExist: true });

  const matches = await fg(input.pattern, {
    cwd: root,
    absolute: true,
    dot: false,
    onlyFiles: true,
    followSymbolicLinks: false,
    suppressErrors: true,
  });

  const withStats = await Promise.all(
    matches.map(async (p) => ({
      p,
      mtime: (await stat(p).catch(() => null))?.mtimeMs ?? 0,
    })),
  );
  withStats.sort((a, b) => b.mtime - a.mtime);
  const sorted = withStats.map(({ p }) => p);

  const truncated = sorted.length > headLimit;
  const kept = truncated ? sorted.slice(0, headLimit) : sorted;

  return { paths: kept, total: sorted.length, truncated };
}

// ---------------------------------------------------------------------------
// grep
// ---------------------------------------------------------------------------

const GREP_DEFAULT_HEAD_LIMIT = 250;

type GrepInput = {
  pattern: string;
  path?: string;
  glob?: string;
  type?: string;
  output_mode?: "content" | "files_with_matches" | "count";
  case_insensitive?: boolean;
  line_numbers?: boolean;
  context?: number;
  multiline?: boolean;
  head_limit?: number;
};

export async function grepTool(
  cfg: FsConfig,
  input: GrepInput,
): Promise<Record<string, unknown>> {
  const mode = input.output_mode ?? "files_with_matches";
  const headLimit = input.head_limit ?? GREP_DEFAULT_HEAD_LIMIT;
  const searchPath = await resolveAllowed(cfg.policy, input.path, { mustExist: true });

  const args = buildGrepArgs({ ...input, output_mode: mode }, searchPath);
  const { stdout, exitCode } = await runRg(args);
  if (exitCode === 2) throw new Error(stdout || "ripgrep error");

  const lines = stdout.length ? stdout.split("\n").filter(Boolean) : [];
  const totalCount = mode === "count" ? sumCounts(lines) : lines.length;
  const truncated = lines.length > headLimit;
  const kept = truncated ? lines.slice(0, headLimit) : lines;

  return { mode, results: kept.join("\n"), match_count: totalCount, truncated };
}

function buildGrepArgs(
  input: GrepInput & { output_mode: "content" | "files_with_matches" | "count" },
  searchPath: string,
): string[] {
  const args: string[] = [];

  switch (input.output_mode) {
    case "files_with_matches":
      args.push("--files-with-matches");
      break;
    case "count":
      args.push("--count-matches");
      break;
    case "content":
      if (input.line_numbers ?? true) args.push("--line-number");
      if (input.context !== undefined) args.push(`--context=${input.context}`);
      break;
  }

  if (input.case_insensitive) args.push("--ignore-case");
  if (input.multiline) args.push("--multiline", "--multiline-dotall");
  if (input.glob) args.push("--glob", input.glob);
  if (input.type) args.push("--type", input.type);

  args.push("--", input.pattern, searchPath);
  return args;
}

function sumCounts(lines: string[]): number {
  let total = 0;
  for (const line of lines) {
    const tail = line.split(":").pop();
    const n = tail ? parseInt(tail, 10) : 0;
    if (!Number.isNaN(n)) total += n;
  }
  return total;
}

function runRg(args: string[]): Promise<{ stdout: string; exitCode: number }> {
  return new Promise((resolve, reject) => {
    execFile(
      rgPath,
      args,
      { timeout: TIMEOUT_MS, maxBuffer: MAX_BUFFER, windowsHide: true },
      (error, stdout, stderr) => {
        const exitCode =
          error && "code" in error && typeof error.code === "number" ? error.code : 0;
        if (error && exitCode !== 1) {
          if ("killed" in error && error.killed) {
            return reject(new Error(`timed out after ${TIMEOUT_MS / 1000}s`));
          }
          return reject(new Error(stderr || error.message));
        }
        resolve({ stdout, exitCode });
      },
    );
  });
}

// ---------------------------------------------------------------------------
// bash
// ---------------------------------------------------------------------------

const RESOLVED_BASH_SHELL = resolveBashShell();
const WIN_DRIVE_RE = /^[A-Za-z]:[\\/]/;
const UNC_PREFIX = "\\\\";

export async function bashTool(
  cfg: FsConfig,
  input: { command: string },
): Promise<Record<string, unknown>> {
  const pathGuardEnabled = parseEnvBool("FILESYSTEM_BASH_PATH_GUARD", true);
  const allowlist = readAllowlist("FILESYSTEM_BASH_ALLOWED_COMMANDS");

  if (allowlist.mode === "deny_all") {
    throw new Error(
      "bash is disabled (FILESYSTEM_BASH_ALLOWED_COMMANDS is set to empty — kill switch). " +
        "Unset the env var or list permitted first-tokens to re-enable.",
    );
  }
  if (allowlist.mode === "list") {
    const firstToken = extractFirstToken(input.command);
    if (firstToken === undefined) throw new Error("bash: command is empty");
    if (!allowlist.set.has(firstToken)) {
      const allowed = [...allowlist.set].sort().join(", ");
      throw new Error(
        `bash: command "${firstToken}" is not in FILESYSTEM_BASH_ALLOWED_COMMANDS allowlist (allowed: ${allowed}). ` +
          "Note: only the first token is checked — pipes / chains / subshells / command substitution are not decomposed.",
      );
    }
  }

  if (pathGuardEnabled) {
    const violation = await checkPathGuard(input.command, cfg.policy);
    if (violation !== null) throw new Error(violation);
  }

  return await runCommand(input.command, cfg.workingDir);
}

function resolveBashShell(): string {
  const override = process.env.FILESYSTEM_BASH_SHELL?.trim();
  if (override) return override;
  if (!IS_WINDOWS) return "/bin/bash";

  const candidates: string[] = [
    "C:\\Program Files\\Git\\bin\\bash.exe",
    "C:\\Program Files\\Git\\usr\\bin\\bash.exe",
    "C:\\Program Files (x86)\\Git\\bin\\bash.exe",
  ];
  if (process.env.PROGRAMFILES) {
    candidates.push(`${process.env.PROGRAMFILES}\\Git\\bin\\bash.exe`);
  }
  for (const p of candidates) {
    if (existsSync(p)) return p;
  }
  throw new Error(
    "filesystem__bash: no bash shell found. Install Git for Windows " +
      "(https://git-scm.com/download/win) or set FILESYSTEM_BASH_SHELL to a bash binary.",
  );
}

function extractFirstToken(command: string): string | undefined {
  const match = command.trim().match(/^\S+/);
  return match ? match[0] : undefined;
}

function parseEnvBool(name: string, fallback: boolean): boolean {
  const raw = process.env[name];
  if (raw === undefined || raw === "") return fallback;
  const v = raw.trim().toLowerCase();
  if (v === "0" || v === "false" || v === "no" || v === "off") return false;
  if (v === "1" || v === "true" || v === "yes" || v === "on") return true;
  return fallback;
}

interface AllowlistConfig {
  mode: "unset" | "deny_all" | "list";
  set: Set<string>;
}

function readAllowlist(name: string): AllowlistConfig {
  const raw = process.env[name];
  if (raw === undefined) return { mode: "unset", set: new Set() };
  const trimmed = raw.trim();
  if (trimmed === "") return { mode: "deny_all", set: new Set() };
  const items = trimmed
    .split(",")
    .map((s) => s.trim())
    .filter((s) => s.length > 0);
  return { mode: "list", set: new Set(items) };
}

function findPathCandidates(command: string): string[] {
  const candidates: string[] = [];
  const cleaned = command.replace(/['"]/g, " ");
  const tokens = cleaned.split(/[\s=]+/).filter((t) => t.length > 0);

  for (const raw of tokens) {
    const token = raw.replace(/^[;&|()<>{}]+/, "").replace(/[;&|()<>{}]+$/, "");
    if (token.length === 0) continue;
    if (looksLikeAbsolutePath(token) || looksLikeTraversal(token)) {
      candidates.push(token);
    }
  }
  return candidates;
}

function looksLikeAbsolutePath(token: string): boolean {
  if (IS_WINDOWS) {
    return WIN_DRIVE_RE.test(token) || token.startsWith(UNC_PREFIX);
  }
  return token.startsWith("/") && token.length > 1;
}

function looksLikeTraversal(token: string): boolean {
  const normalised = token.replace(/\\/g, "/");
  if (normalised === "..") return true;
  if (normalised.startsWith("../")) return true;
  if (normalised.includes("/../")) return true;
  if (normalised.endsWith("/..")) return true;
  return false;
}

async function checkPathGuard(command: string, policy: PathPolicy): Promise<string | null> {
  const candidates = findPathCandidates(command);
  if (candidates.length === 0) return null;

  for (const cand of candidates) {
    if (!(await isPathAllowed(policy, cand))) {
      const rootList = [policy.workingDir, ...policy.extraAllowed].join(IS_WINDOWS ? "; " : ":");
      return (
        `bash: refusing to execute — command references path "${cand}" outside the allowed roots. ` +
        `Allowed: ${rootList}. ` +
        "Set FILESYSTEM_BASH_PATH_GUARD=false to disable, or add the root to FILESYSTEM_ALLOWED_DIRS. " +
        "(Accident prevention only — not adversarial sandboxing.)"
      );
    }
  }
  return null;
}

function runCommand(command: string, cwd: string): Promise<Record<string, unknown>> {
  return new Promise((resolve) => {
    const child = execFile(
      RESOLVED_BASH_SHELL,
      ["-c", command],
      { cwd, timeout: TIMEOUT_MS, maxBuffer: MAX_BUFFER, windowsHide: true },
      (error, stdout, stderr) => {
        const outputTruncated =
          !!error &&
          "code" in error &&
          error.code === "ERR_CHILD_PROCESS_STDIO_MAXBUFFER_EXCEEDED";

        if (outputTruncated) {
          resolve({ stdout: stdout ?? "", stderr: stderr ?? "", exit_code: -1, timed_out: false, output_truncated: true });
          return;
        }
        if (error && "killed" in error && error.killed) {
          resolve({ stdout: stdout ?? "", stderr: stderr ?? "", exit_code: -1, timed_out: true, output_truncated: false });
          return;
        }
        const exitCode =
          error && "code" in error && typeof error.code === "number"
            ? error.code
            : (child.exitCode ?? 0);
        resolve({ stdout: stdout ?? "", stderr: stderr ?? "", exit_code: exitCode, timed_out: false, output_truncated: false });
      },
    );
  });
}

// ---------------------------------------------------------------------------
// save_memory
// ---------------------------------------------------------------------------

export async function saveMemoryTool(
  cfg: FsConfig,
  input: { file: string; content: string },
): Promise<Record<string, unknown>> {
  if (!cfg.memoryDir) {
    throw new Error("save_memory is unavailable — no MemoryDir configured (Filesystem.MemoryDir).");
  }
  if (!input.file.endsWith(".md")) {
    throw new Error("Only .md files are allowed in the memory directory.");
  }
  if (input.file.includes("/") || input.file.includes("\\") || input.file.includes("..")) {
    throw new Error("'file' must be a plain filename (no path separators or '..').");
  }

  const targetPath = path.join(cfg.memoryDir, input.file);
  await mkdir(cfg.memoryDir, { recursive: true });
  await writeFile(targetPath, input.content, "utf-8");

  const structured: Record<string, unknown> = {
    success: true,
    file: input.file,
    message: `Successfully saved ${input.file}`,
  };

  if (input.file === "MEMORY.md") {
    let lineCount = input.content.split("\n").length;
    if (input.content.endsWith("\n")) lineCount--;
    structured.line_count = lineCount;
    if (lineCount > cfg.memoryMaxLines) {
      structured.warning =
        `MEMORY.md is ${lineCount} lines but only the first ${cfg.memoryMaxLines} lines are loaded into context. ` +
        `Consider moving detailed content to topic files and linking from MEMORY.md.`;
    }
  }

  return structured;
}

// ---------------------------------------------------------------------------
// shared helpers
// ---------------------------------------------------------------------------

function isBinary(buf: Buffer): boolean {
  const len = Math.min(buf.length, BINARY_SNIFF_BYTES);
  for (let i = 0; i < len; i++) {
    if (buf[i] === 0) return true;
  }
  return false;
}

function formatBytes(n: number): string {
  if (n < 1024) return `${n}B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(0)}KB`;
  return `${(n / (1024 * 1024)).toFixed(1)}MB`;
}

function splitLines(text: string): string[] {
  if (text === "") return [];
  const lines = text.split("\n");
  if (lines.length > 0 && lines[lines.length - 1] === "") {
    lines.pop();
  }
  return lines;
}

// ---------------------------------------------------------------------------
// dispatcher
// ---------------------------------------------------------------------------

export async function callFilesystemTool(
  cfg: FsConfig,
  name: string,
  args: Record<string, unknown>,
): Promise<unknown> {
  switch (name) {
    case "read_file":
      return readFileTool(cfg, args as { path: string; offset?: number; limit?: number });
    case "write_file":
      return writeFileTool(cfg, args as { path: string; content: string });
    case "append_file":
      return appendFileTool(cfg, args as { path: string; content: string });
    case "delete_file":
      return deleteFileTool(cfg, args as { path: string });
    case "edit_file":
      return editFileTool(
        cfg,
        args as { path: string; old_string: string; new_string: string; replace_all?: boolean },
      );
    case "glob":
      return globTool(cfg, args as { pattern: string; path?: string; head_limit?: number });
    case "grep":
      return grepTool(cfg, args as GrepInput);
    case "bash":
      return bashTool(cfg, args as { command: string });
    case "save_memory":
      return saveMemoryTool(cfg, args as { file: string; content: string });
    default:
      throw new Error(`filesystem: unknown tool '${name}'`);
  }
}

export const FILESYSTEM_TOOL_NAMES = [
  "read_file",
  "write_file",
  "append_file",
  "delete_file",
  "edit_file",
  "glob",
  "grep",
  "bash",
  "save_memory",
] as const;
