/**
 * PathPolicy — containment for the native filesystem tools.
 *
 * Verbatim port of mcp_servers/ts/packages/filesystem/src/paths.ts so that
 * codegen tasks enforce the SAME sandbox the agent's native filesystem tools
 * do: every path is resolved (symlinks included) and must sit inside the
 * working dir, an extra allowed dir, or a readonly dir; mutating ops are
 * additionally rejected inside readonly roots. Symlink-escape is defended by
 * comparing realpaths.
 *
 * DO NOT EDIT THIS FILE — keep it in sync with the filesystem MCP package.
 */

import { realpath } from "node:fs/promises";
import path from "node:path";

const IS_WINDOWS = process.platform === "win32";

export interface PathPolicy {
  workingDir: string;
  extraAllowed: string[];
  readonly: string[];
}

export function loadPathPolicy(
  workingDir: string,
  allowedDirsEnv: string | undefined,
  readonlyDirsEnv?: string | undefined,
): PathPolicy {
  const parseList = (env: string | undefined): string[] =>
    (env ?? "")
      .split(path.delimiter)
      .map((p) => p.trim())
      .filter(Boolean)
      .map((p) => path.resolve(p));
  return {
    workingDir: path.resolve(workingDir),
    extraAllowed: parseList(allowedDirsEnv),
    readonly: parseList(readonlyDirsEnv),
  };
}

export async function resolveAllowed(
  policy: PathPolicy,
  input: string | undefined,
  opts: { mustExist: boolean } = { mustExist: true },
): Promise<string> {
  const raw = input ?? policy.workingDir;
  const resolved = path.isAbsolute(raw) ? path.resolve(raw) : path.resolve(policy.workingDir, raw);

  const real = opts.mustExist
    ? await realpath(resolved)
    : await realpathExistingAncestor(resolved);

  const roots = [policy.workingDir, ...policy.extraAllowed, ...policy.readonly];
  for (const root of roots) {
    const realRoot = await realpath(root).catch(() => root);
    if (isInside(real, realRoot)) return real;
  }

  const allowed = roots.map((r) => `  - ${r}`).join("\n");
  throw new Error(
    `Path "${raw}" is outside the allowed roots. Allowed:\n${allowed}\n` +
    `(set FILESYSTEM_ALLOWED_DIRS to add more, separated by "${path.delimiter}")`,
  );
}

export async function requireWritable(policy: PathPolicy, resolved: string): Promise<void> {
  if (policy.readonly.length === 0) return;
  for (const root of policy.readonly) {
    const realRoot = await realpath(root).catch(() => root);
    if (isInside(resolved, realRoot)) {
      throw new Error(
        `Path "${resolved}" is in a read-only root (${root}). ` +
        `Mutating operations (write_file, append_file, edit_file, delete_file) are not permitted here.`,
      );
    }
  }
}

export async function isPathAllowed(policy: PathPolicy, candidate: string): Promise<boolean> {
  try {
    await resolveAllowed(policy, candidate, { mustExist: false });
    return true;
  } catch {
    return false;
  }
}

function isInside(target: string, root: string): boolean {
  const t = IS_WINDOWS ? target.toLowerCase() : target;
  const r = IS_WINDOWS ? root.toLowerCase() : root;
  if (t === r) return true;
  const rWithSep = r.endsWith(path.sep) ? r : r + path.sep;
  return t.startsWith(rWithSep);
}

async function realpathExistingAncestor(p: string): Promise<string> {
  let current = p;
  const tail: string[] = [];
  while (true) {
    try {
      const real = await realpath(current);
      return tail.length ? path.join(real, ...tail.reverse()) : real;
    } catch {
      const parent = path.dirname(current);
      if (parent === current) return p;
      tail.push(path.basename(current));
      current = parent;
    }
  }
}
