/**
 * Native (in-process) system-info tools for codegen tasks.
 *
 * Node port of src/micro_x_agent_loop/native_tools/system_info.py (which is
 * itself the native replacement for the old system-info MCP server). Three
 * read-only tools: system_info / disk_info / network_info. The Python version
 * uses psutil; this uses Node's `os` + `fs.statfs`, producing the same
 * human-readable text shape.
 *
 * DO NOT EDIT THIS FILE — keep it in sync with the Python native tool.
 */

import os from "node:os";
import { statfs } from "node:fs/promises";

const IS_WINDOWS = process.platform === "win32";

export async function systemInfoTool(): Promise<string> {
  const totalGb = os.totalmem() / 1024 ** 3;
  const uptimeS = Math.floor(os.uptime());
  const days = Math.floor(uptimeS / 86400);
  const hours = Math.floor((uptimeS % 86400) / 3600);
  const mins = Math.floor((uptimeS % 3600) / 60);
  const username = (() => {
    try {
      return os.userInfo().username;
    } catch {
      return "unknown";
    }
  })();

  return (
    "System Information\n" +
    "==================\n" +
    `OS:              ${os.type()} ${os.release()} (${os.platform()}/${os.arch()})\n` +
    `Machine Name:    ${os.hostname()}\n` +
    `Current User:    ${username}\n` +
    `Processor Count: ${os.cpus().length}\n` +
    `Total Memory:    ${totalGb.toFixed(1)} GB\n` +
    `System Uptime:   ${days}d ${hours}h ${mins}m\n` +
    `Node Runtime:    ${process.release.name} ${process.version}`
  );
}

export async function diskInfoTool(): Promise<string> {
  const lines = ["Disk Information", "================"];

  const mountpoints = IS_WINDOWS
    ? "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("").map((d) => `${d}:\\`)
    : ["/"];

  for (const mount of mountpoints) {
    let fs;
    try {
      fs = await statfs(mount);
    } catch {
      continue; // drive letter not present / not ready
    }
    const total = fs.blocks * fs.bsize;
    if (total <= 0) continue;
    const free = fs.bavail * fs.bsize;
    const totalGb = total / 1024 ** 3;
    const freeGb = free / 1024 ** 3;
    const usedPct = total > 0 ? ((total - free) / total) * 100 : 0;
    lines.push(
      "",
      `Drive ${mount}`,
      `  Mountpoint:  ${mount}`,
      `  Total Size:  ${totalGb.toFixed(1)} GB`,
      `  Free Space:  ${freeGb.toFixed(1)} GB`,
      `  Used:        ${usedPct.toFixed(1)}%`,
    );
  }
  return lines.join("\n");
}

export async function networkInfoTool(): Promise<string> {
  const lines = ["Network Interfaces", "=================="];
  const ifaces = os.networkInterfaces();
  for (const [name, addrs] of Object.entries(ifaces)) {
    if (!addrs || addrs.length === 0) continue;
    const external = addrs.filter((a) => !a.internal);
    if (external.length === 0) continue;
    lines.push("", `${name}`);
    for (const addr of external) {
      if (addr.family === "IPv4") {
        lines.push(`  IPv4:   ${addr.address}`);
      } else if (addr.family === "IPv6") {
        lines.push(`  IPv6:   ${addr.address.split("%")[0]}`);
      }
    }
  }
  return lines.join("\n");
}

export async function callSystemInfoTool(name: string): Promise<unknown> {
  switch (name) {
    case "system_info":
      return systemInfoTool();
    case "disk_info":
      return diskInfoTool();
    case "network_info":
      return networkInfoTool();
    default:
      throw new Error(`system-info: unknown tool '${name}'`);
  }
}

export const SYSTEM_INFO_TOOL_NAMES = ["system_info", "disk_info", "network_info"] as const;
