"""Console app entry point - DO NOT EDIT THIS FILE.

Create task.py with SERVERS and run_task() instead. See ADAPT-PROMPT.md.
"""

import asyncio
import json
import os
import sys
from pathlib import Path
from typing import Any

from dotenv import load_dotenv

from .mcp_client import McpClient
from .task import SERVERS, run_task
from .utils import write_file  # noqa: F401 - re-exported for backwards compat

INHERITED_CONFIG_ENV = "MICRO_X_AGENT_CONFIG_JSON"


def load_json_config(config_path: str | None = None) -> tuple[dict, str]:
    """Load config with ConfigFile indirection and --config CLI support."""
    inherited_config = os.environ.get(INHERITED_CONFIG_ENV)
    if inherited_config:
        return json.loads(inherited_config), f"{INHERITED_CONFIG_ENV} (inherited)"

    if config_path:
        p = Path(config_path)
        if not p.exists():
            raise FileNotFoundError(f"Config file not found: {p}")
        with open(p) as f:
            return json.load(f), str(p)

    default_path = Path.cwd() / "config.json"
    if not default_path.exists():
        return {}, "config.json (defaults)"

    with open(default_path) as f:
        data = json.load(f)

    config_file = data.get("ConfigFile")
    if config_file:
        target = Path.cwd() / config_file
        if not target.exists():
            raise FileNotFoundError(f"ConfigFile target not found: {target}")
        with open(target) as f:
            return json.load(f), str(config_file)

    return data, "config.json"


async def connect_servers(
    server_configs: dict[str, dict[str, Any]],
) -> dict[str, McpClient]:
    """Connect MCP servers in parallel. Skips failures with a warning."""
    clients: dict[str, McpClient] = {}
    tasks: dict[str, asyncio.Task] = {}

    for name, cfg in server_configs.items():
        command = cfg.get("command", "")
        args = cfg.get("args", [])
        env = cfg.get("env")
        if not command:
            continue
        client = McpClient(name)
        clients[name] = client
        tasks[name] = asyncio.create_task(client.connect(command, args, env))

    connected: dict[str, McpClient] = {}
    for name, task in tasks.items():
        try:
            await task
            connected[name] = clients[name]
            print(f"  {name}: connected")
        except Exception as ex:
            print(f"  {name}: FAILED ({ex})")

    return connected


async def main() -> None:
    load_dotenv()

    config_path = None
    args = sys.argv[1:]
    if "--config" in args:
        idx = args.index("--config")
        if idx + 1 < len(args):
            config_path = args[idx + 1]

    config, source = load_json_config(config_path)
    print(f"Config: {source}")

    mcp_configs = config.get("McpServers", {})
    needed = {k: v for k, v in mcp_configs.items() if k in SERVERS}

    if needed:
        print(f"\nConnecting MCP servers...")
        clients = await connect_servers(needed)
        print(f"{len(clients)}/{len(needed)} servers connected")
    else:
        print(f"\nNo MCP servers found for: {SERVERS}")
        clients = {}

    try:
        await run_task(clients, config)
    finally:
        if clients:
            print("\nShutting down MCP servers...")
            for client in clients.values():
                try:
                    await client.close()
                except Exception:
                    pass
            print("Done.")


def _run() -> None:
    _original_hook = sys.unraisablehook

    def _quiet_hook(args) -> None:
        if args.exc_type is ValueError and "closed pipe" in str(args.exc_value):
            return
        if args.exc_type is ResourceWarning and "unclosed transport" in str(args.exc_value):
            return
        _original_hook(args)

    sys.unraisablehook = _quiet_hook
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print("\nInterrupted.")
        sys.exit(1)


if __name__ == "__main__":
    _run()
