"""Test infrastructure — DO NOT EDIT THIS FILE.

Provides base test case and fixtures for generated task app tests.

Usage in test files:
    from tools.<task_name>.test_base import TaskTestCase

    class TestMyModule(TaskTestCase):
        def test_something(self):
            job = self.make_jobserve_job(title="AI Architect", rate="£700 PER DAY")
            ...
"""

import unittest
from pathlib import Path

# Auto-detect package name from directory location
PACKAGE_NAME = "tools." + Path(__file__).parent.name


class TaskTestCase(unittest.TestCase):
    """Base test case with fixtures for job-processing task apps."""

    @staticmethod
    def make_jobserve_job(**overrides) -> dict:
        """Create a JobServe job dict with sensible defaults."""
        job = {
            "title": "Senior Software Engineer",
            "rate": "£600 PER DAY",
            "location": "London",
            "duration": "6 months",
            "ir35": "Outside IR35",
            "agency": "Test Agency",
            "ref": "TEST-001",
            "tech": ["Python", "Azure"],
            "apply_url": "https://example.com/apply",
            "spec_url": "https://example.com/spec",
            "body": "Test job description with Python and Azure skills.",
            "date": "Mon, 02 Mar 2026",
            "subject": "Test Subject",
            "from": "test@example.com",
            "source": "jobserve",
        }
        job.update(overrides)
        return job

    @staticmethod
    def make_linkedin_job(**overrides) -> dict:
        """Create a LinkedIn job dict with sensible defaults."""
        job = {
            "title": "AI Engineer",
            "company": "Test Corp",
            "location": "London, United Kingdom",
            "posted": "2 days ago",
            "salary": "",
            "url": "https://linkedin.com/jobs/view/test-123",
            "detail": {
                "title": "AI Engineer",
                "company": "Test Corp",
                "location": "London, United Kingdom",
                "description": "Test job description with LLM and agent skills.",
                "url": "https://linkedin.com/jobs/view/test-123",
            },
            "source": "linkedin",
        }
        job.update(overrides)
        return job

    @staticmethod
    def make_email(subject: str = "Test Alert", body: str = "", **overrides) -> dict:
        """Create a raw email dict as returned by gmail_read."""
        email = {
            "messageId": "msg-test-001",
            "from": "alerts@example.com",
            "to": "user@example.com",
            "date": "Mon, 02 Mar 2026 10:00:00 +0000",
            "subject": subject,
            "body": body,
        }
        email.update(overrides)
        return email
