"""Shared utilities — DO NOT EDIT THIS FILE."""

import asyncio
from pathlib import Path


def get_output_dir(config: dict) -> Path:
    """Return WorkingDirectory from config, or CWD."""
    wd = config.get("WorkingDirectory")
    if wd:
        p = Path(wd)
        p.mkdir(parents=True, exist_ok=True)
        return p
    return Path.cwd()


def _resolve_path(path: str, config: dict | None) -> Path:
    """Resolve path against WorkingDirectory from config."""
    p = Path(path)
    if not p.is_absolute() and config:
        p = get_output_dir(config) / p
    p.parent.mkdir(parents=True, exist_ok=True)
    return p


def _write_sync(path: str, content: str, config: dict | None) -> Path:
    p = _resolve_path(path, config)
    with open(p, "w", encoding="utf-8") as f:
        f.write(content)
    return p


def _append_sync(path: str, content: str, config: dict | None) -> Path:
    p = _resolve_path(path, config)
    with open(p, "a", encoding="utf-8") as f:
        f.write(content)
    return p


async def write_file(path: str, content: str, config: dict | None = None) -> Path:
    """Write UTF-8 file (overwrites). Relative paths resolve against WorkingDirectory."""
    return await asyncio.to_thread(_write_sync, path, content, config)


async def append_file(path: str, content: str, config: dict | None = None) -> Path:
    """Append to UTF-8 file. Relative paths resolve against WorkingDirectory."""
    return await asyncio.to_thread(_append_sync, path, content, config)
