/**
 * Task app entry point — DO NOT EDIT THIS FILE.
 *
 * Create task.ts with SERVERS and runTask() instead.
 */

import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import "dotenv/config";

import { McpClient } from "./mcp-client.js";
import { SERVERS, runTask } from "./task.js";

interface McpServerConfig {
  command?: string;
  args?: string[];
  env?: Record<string, string>;
}

function loadJsonConfig(configPath?: string): [Record<string, unknown>, string] {
  let p: string;
  let source: string;

  if (configPath) {
    p = resolve(configPath);
    source = p;
  } else {
    p = resolve(process.cwd(), "config.json");
    source = "config.json";
  }

  let data: Record<string, unknown>;
  try {
    data = JSON.parse(readFileSync(p, "utf-8"));
  } catch {
    return [{}, "config.json (defaults)"];
  }

  // Follow ConfigFile indirection — resolve relative to the config file's directory
  const configFile = data["ConfigFile"];
  if (typeof configFile === "string") {
    const configDir = dirname(p);
    const target = resolve(configDir, configFile);
    const targetData = JSON.parse(readFileSync(target, "utf-8"));
    return [targetData, configFile];
  }

  return [data, source];
}

async function connectServers(
  serverConfigs: Record<string, McpServerConfig>,
): Promise<Record<string, McpClient>> {
  const entries = Object.entries(serverConfigs).filter(([, cfg]) => cfg.command);
  const results = await Promise.allSettled(
    entries.map(async ([name, cfg]) => {
      const client = new McpClient(name);
      await client.connect(cfg.command!, cfg.args ?? [], cfg.env);
      console.log(`  ${name}: connected`);
      return [name, client] as const;
    }),
  );

  const connected: Record<string, McpClient> = {};
  for (const result of results) {
    if (result.status === "fulfilled") {
      const [name, client] = result.value;
      connected[name] = client;
    } else {
      console.error(`  server FAILED: ${result.reason}`);
    }
  }
  return connected;
}

async function main(): Promise<void> {
  let configPath: string | undefined;
  const args = process.argv.slice(2);
  const configIdx = args.indexOf("--config");
  if (configIdx !== -1 && configIdx + 1 < args.length) {
    configPath = args[configIdx + 1];
  }

  const [config, source] = loadJsonConfig(configPath);
  console.log(`Config: ${source}`);

  const mcpConfigs = (config["McpServers"] ?? {}) as Record<string, McpServerConfig>;
  const needed: Record<string, McpServerConfig> = {};
  for (const name of SERVERS) {
    if (mcpConfigs[name]) needed[name] = mcpConfigs[name];
  }

  let clients: Record<string, McpClient> = {};
  if (Object.keys(needed).length > 0) {
    console.log("\nConnecting MCP servers...");
    clients = await connectServers(needed);
    console.log(`${Object.keys(clients).length}/${Object.keys(needed).length} servers connected`);
  } else {
    console.log(`\nNo MCP servers found for: ${SERVERS.join(", ")}`);
  }

  try {
    await runTask(clients, config);
  } finally {
    if (Object.keys(clients).length > 0) {
      console.log("\nShutting down MCP servers...");
      await Promise.all(
        Object.values(clients).map((c) => c.close().catch(() => {})),
      );
      console.log("Done.");
    }
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
