/**
 * Task app entry point — DO NOT EDIT THIS FILE.
 *
 * Dual-mode:
 *   Default:  Starts an MCP server exposing the tool defined in task.ts
 *   --run:    Executes the tool directly and prints the result (standalone mode)
 *
 * Create task.ts with SERVERS, TOOL_NAME, TOOL_DESCRIPTION,
 * TOOL_INPUT_SCHEMA, and handleTool() instead.
 */

import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import "dotenv/config";

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";

import { McpClient } from "./mcp-client.js";
import {
  SERVERS,
  TOOL_NAME,
  TOOL_DESCRIPTION,
  TOOL_INPUT_SCHEMA,
  handleTool,
} from "./task.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const isRunMode = process.argv.includes("--run");

// In MCP server mode, stdout is the transport — all logging goes to stderr
const log = isRunMode
  ? console.log.bind(console)
  : (...args: unknown[]) => process.stderr.write(args.map(String).join(" ") + "\n");

/* ------------------------------------------------------------------ */
/*  Config                                                             */
/* ------------------------------------------------------------------ */

interface McpServerConfig {
  command?: string;
  args?: string[];
  env?: Record<string, string>;
}

function loadJsonConfig(configPath?: string): [Record<string, unknown>, string] {
  let p: string;
  let source: string;

  if (configPath) {
    p = resolve(configPath);
    source = p;
  } else {
    p = resolve(process.cwd(), "config.json");
    source = "config.json";
  }

  let data: Record<string, unknown>;
  try {
    data = JSON.parse(readFileSync(p, "utf-8"));
  } catch {
    return [{}, "config.json (defaults)"];
  }

  // Follow ConfigFile indirection — resolve relative to the config file's directory
  const configFile = data["ConfigFile"];
  if (typeof configFile === "string") {
    const configDir = dirname(p);
    const target = resolve(configDir, configFile);
    const targetData = JSON.parse(readFileSync(target, "utf-8"));
    return [targetData, configFile];
  }

  return [data, source];
}

function loadProfile(): Record<string, unknown> {
  try {
    return JSON.parse(readFileSync(resolve(__dirname, "../profile.json"), "utf-8"));
  } catch {
    return {};
  }
}

function parseConfigPath(): string | undefined {
  const args = process.argv.slice(2);
  const idx = args.indexOf("--config");
  return idx !== -1 && idx + 1 < args.length ? args[idx + 1] : undefined;
}

/* ------------------------------------------------------------------ */
/*  MCP client connections (upstream servers)                          */
/* ------------------------------------------------------------------ */

async function connectUpstream(
  config: Record<string, unknown>,
): Promise<Record<string, McpClient>> {
  const mcpConfigs = (config["McpServers"] ?? {}) as Record<string, McpServerConfig>;
  const needed: Record<string, McpServerConfig> = {};
  for (const name of SERVERS) {
    if (mcpConfigs[name]) needed[name] = mcpConfigs[name];
  }

  if (Object.keys(needed).length === 0) {
    if (SERVERS.length > 0) log(`No MCP servers found for: ${SERVERS.join(", ")}`);
    return {};
  }

  log("Connecting MCP servers...");
  const entries = Object.entries(needed).filter(([, cfg]) => cfg.command);
  const results = await Promise.allSettled(
    entries.map(async ([name, cfg]) => {
      const client = new McpClient(name);
      await client.connect(cfg.command!, cfg.args ?? [], cfg.env);
      log(`  ${name}: connected`);
      return [name, client] as const;
    }),
  );

  const connected: Record<string, McpClient> = {};
  for (const result of results) {
    if (result.status === "fulfilled") {
      const [name, client] = result.value;
      connected[name] = client;
    } else {
      log(`  server FAILED: ${result.reason}`);
    }
  }
  log(`${Object.keys(connected).length}/${Object.keys(needed).length} servers connected`);
  return connected;
}

async function shutdownClients(clients: Record<string, McpClient>): Promise<void> {
  if (Object.keys(clients).length === 0) return;
  log("Shutting down MCP servers...");
  await Promise.all(Object.values(clients).map((c) => c.close().catch(() => {})));
  log("Done.");
}

/* ------------------------------------------------------------------ */
/*  MCP server mode (default)                                          */
/* ------------------------------------------------------------------ */

async function runServer(): Promise<void> {
  const [config, source] = loadJsonConfig(parseConfigPath());
  log(`Config: ${source}`);

  const profile = loadProfile();

  // Lazy upstream connection — connect on first tool call, not at startup
  let clients: Record<string, McpClient> | null = null;
  async function getClients(): Promise<Record<string, McpClient>> {
    if (clients) return clients;
    clients = await connectUpstream(config);
    return clients;
  }

  const server = new McpServer(
    { name: TOOL_NAME, version: "0.1.0" },
    { capabilities: { tools: {} } },
  );

  server.tool(TOOL_NAME, TOOL_DESCRIPTION, TOOL_INPUT_SCHEMA, async (params) => {
    const c = await getClients();
    const result = await handleTool(params, c, profile, config);
    return {
      content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }],
    };
  });

  const transport = new StdioServerTransport();
  await server.connect(transport);

  // Cleanup on exit
  const cleanup = async () => {
    if (clients) await shutdownClients(clients);
    process.exit(0);
  };
  process.on("SIGINT", cleanup);
  process.on("SIGTERM", cleanup);
}

/* ------------------------------------------------------------------ */
/*  Standalone mode (--run)                                            */
/* ------------------------------------------------------------------ */

async function runDirect(): Promise<void> {
  const [config, source] = loadJsonConfig(parseConfigPath());
  console.log(`Config: ${source}`);

  const profile = loadProfile();
  const clients = await connectUpstream(config);

  try {
    // Parse --params '{"days": 7}' if provided
    let params: Record<string, unknown> = {};
    const args = process.argv.slice(2);
    const paramsIdx = args.indexOf("--params");
    if (paramsIdx !== -1 && paramsIdx + 1 < args.length) {
      params = JSON.parse(args[paramsIdx + 1]);
    }

    const result = await handleTool(params, clients, profile, config);
    console.log(JSON.stringify(result, null, 2));
  } finally {
    await shutdownClients(clients);
  }
}

/* ------------------------------------------------------------------ */
/*  Entry                                                              */
/* ------------------------------------------------------------------ */

if (isRunMode) {
  runDirect().catch((err) => {
    console.error(err);
    process.exit(1);
  });
} else {
  runServer().catch((err) => {
    process.stderr.write(`Fatal: ${err}\n`);
    process.exit(1);
  });
}
