/**
 * Task app entry point - DO NOT EDIT THIS FILE.
 *
 * Dual-mode:
 *   Default:  Starts an MCP server exposing the tool defined in task.ts
 *   --run:    Executes the tool directly and prints the result (standalone mode)
 *
 * Create task.ts with SERVERS, TOOL_NAME, TOOL_DESCRIPTION,
 * TOOL_INPUT_SCHEMA, and handleTool() instead.
 */

import { existsSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import "dotenv/config";
import { z } from "zod";

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";

import { McpClient } from "./mcp-client.js";
import {
  SERVERS,
  TOOL_NAME,
  TOOL_DESCRIPTION,
  TOOL_INPUT_SCHEMA,
  handleTool,
} from "./task.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const isRunMode = process.argv.includes("--run");
type ToolParams = Parameters<typeof handleTool>[0];
const isEntrypoint = (() => {
  const argvPath = process.argv[1];
  return argvPath ? resolve(argvPath) === fileURLToPath(import.meta.url) : false;
})();

// In MCP server mode, stdout is the transport - all logging goes to stderr
const log = isRunMode
  ? console.log.bind(console)
  : (...args: unknown[]) => process.stderr.write(args.map(String).join(" ") + "\n");

/* ------------------------------------------------------------------ */
/*  Config                                                             */
/* ------------------------------------------------------------------ */

interface McpServerConfig {
  command?: string;
  args?: string[];
  env?: Record<string, string>;
}

const INHERITED_CONFIG_ENV = "MICRO_X_AGENT_CONFIG_JSON";
const ENV_VAR_RE = /\$\{([^}]+)\}/g;

function deepMerge(
  base: Record<string, unknown>,
  overlay: Record<string, unknown>,
): Record<string, unknown> {
  const result: Record<string, unknown> = { ...base };
  for (const [key, value] of Object.entries(overlay)) {
    const current = result[key];
    if (
      current &&
      typeof current === "object" &&
      !Array.isArray(current) &&
      value &&
      typeof value === "object" &&
      !Array.isArray(value)
    ) {
      result[key] = deepMerge(
        current as Record<string, unknown>,
        value as Record<string, unknown>,
      );
    } else {
      result[key] = value;
    }
  }
  return result;
}

function expandEnvVars(value: unknown): unknown {
  if (typeof value === "string") {
    return value.replaceAll(ENV_VAR_RE, (_, name: string) => process.env[name] ?? `\${${name}}`);
  }
  if (Array.isArray(value)) {
    return value.map((item) => expandEnvVars(item));
  }
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value).map(([key, item]) => [key, expandEnvVars(item)]),
    );
  }
  return value;
}

function resolveConfigWithBase(
  data: Record<string, unknown>,
  configDir: string,
): Record<string, unknown> {
  const baseFile = data["Base"];
  if (typeof baseFile !== "string" || baseFile.trim() === "") {
    return data;
  }

  const basePath = resolve(configDir, baseFile);
  if (!existsSync(basePath)) {
    throw new Error(`Base config not found: ${basePath} (referenced via 'Base' key)`);
  }

  const baseData = JSON.parse(readFileSync(basePath, "utf-8")) as Record<string, unknown>;
  const resolvedBase = resolveConfigWithBase(baseData, dirname(basePath));
  const overlay = Object.fromEntries(Object.entries(data).filter(([key]) => key !== "Base"));
  return deepMerge(resolvedBase, overlay);
}

export function loadJsonConfig(configPath?: string): [Record<string, unknown>, string] {
  const inheritedConfig = process.env[INHERITED_CONFIG_ENV];
  if (inheritedConfig) {
    return [
      JSON.parse(inheritedConfig) as Record<string, unknown>,
      `${INHERITED_CONFIG_ENV} (inherited)`,
    ];
  }

  let configPathToLoad: string;
  let source: string;

  if (configPath) {
    configPathToLoad = resolve(configPath);
    source = configPathToLoad;
    if (!existsSync(configPathToLoad)) {
      throw new Error(`Config file not found: ${configPathToLoad}`);
    }
  } else {
    configPathToLoad = resolve(process.cwd(), "config.json");
    source = "config.json";
    if (!existsSync(configPathToLoad)) {
      return [{}, "config.json (defaults)"];
    }
  }

  let data = JSON.parse(readFileSync(configPathToLoad, "utf-8")) as Record<string, unknown>;

  const configFile = data["ConfigFile"];
  if (typeof configFile === "string") {
    const configDir = dirname(configPathToLoad);
    const target = resolve(configDir, configFile);
    if (!existsSync(target)) {
      throw new Error(`ConfigFile target not found: ${target} (referenced from config.json)`);
    }
    data = JSON.parse(readFileSync(target, "utf-8")) as Record<string, unknown>;
    return [
      expandEnvVars(resolveConfigWithBase(data, dirname(target))) as Record<string, unknown>,
      configFile,
    ];
  }

  return [
    expandEnvVars(resolveConfigWithBase(data, dirname(configPathToLoad))) as Record<string, unknown>,
    source,
  ];
}

function loadProfile(): Record<string, unknown> {
  try {
    return JSON.parse(readFileSync(resolve(__dirname, "../profile.json"), "utf-8"));
  } catch {
    return {};
  }
}

function parseConfigPath(): string | undefined {
  const args = process.argv.slice(2);
  const idx = args.indexOf("--config");
  return idx !== -1 && idx + 1 < args.length ? args[idx + 1] : undefined;
}

/* ------------------------------------------------------------------ */
/*  MCP client connections (upstream servers)                          */
/* ------------------------------------------------------------------ */

async function connectUpstream(
  config: Record<string, unknown>,
): Promise<Record<string, McpClient>> {
  const mcpConfigs = (config["McpServers"] ?? {}) as Record<string, McpServerConfig>;
  const needed: Record<string, McpServerConfig> = {};
  for (const name of SERVERS) {
    if (mcpConfigs[name]) needed[name] = mcpConfigs[name];
  }

  if (Object.keys(needed).length === 0) {
    if (SERVERS.length > 0) log(`No MCP servers found for: ${SERVERS.join(", ")}`);
    return {};
  }

  log("Connecting MCP servers...");
  const entries = Object.entries(needed).filter(([, cfg]) => cfg.command);
  const results = await Promise.allSettled(
    entries.map(async ([name, cfg]) => {
      const client = new McpClient(name);
      await client.connect(cfg.command!, cfg.args ?? [], cfg.env);
      log(`  ${name}: connected`);
      return [name, client] as const;
    }),
  );

  const connected: Record<string, McpClient> = {};
  for (const result of results) {
    if (result.status === "fulfilled") {
      const [name, client] = result.value;
      connected[name] = client;
    } else {
      log(`  server FAILED: ${result.reason}`);
    }
  }
  log(`${Object.keys(connected).length}/${Object.keys(needed).length} servers connected`);
  return connected;
}

async function shutdownClients(clients: Record<string, McpClient>): Promise<void> {
  if (Object.keys(clients).length === 0) return;
  log("Shutting down MCP servers...");
  await Promise.all(Object.values(clients).map((c) => c.close().catch(() => {})));
  log("Done.");
}

/* ------------------------------------------------------------------ */
/*  MCP server mode (default)                                          */
/* ------------------------------------------------------------------ */

async function runServer(): Promise<void> {
  const [config, source] = loadJsonConfig(parseConfigPath());
  log(`Config: ${source}`);

  const profile = loadProfile();

  // Lazy upstream connection - connect on first tool call, not at startup
  let clients: Record<string, McpClient> | null = null;
  async function getClients(): Promise<Record<string, McpClient>> {
    if (clients) return clients;
    clients = await connectUpstream(config);
    return clients;
  }

  const server = new McpServer(
    { name: TOOL_NAME, version: "0.1.0" },
    { capabilities: { tools: {} } },
  );

  server.tool(TOOL_NAME, TOOL_DESCRIPTION, TOOL_INPUT_SCHEMA, async (params: ToolParams) => {
    const c = await getClients();
    const result = await handleTool(params, c, profile, config);
    return {
      content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }],
    };
  });

  const transport = new StdioServerTransport();
  await server.connect(transport);

  const cleanup = async () => {
    if (clients) await shutdownClients(clients);
    process.exit(0);
  };
  process.on("SIGINT", cleanup);
  process.on("SIGTERM", cleanup);
}

/* ------------------------------------------------------------------ */
/*  Standalone mode (--run)                                            */
/* ------------------------------------------------------------------ */

async function runDirect(): Promise<void> {
  const [config, source] = loadJsonConfig(parseConfigPath());
  console.log(`Config: ${source}`);

  const profile = loadProfile();
  const clients = await connectUpstream(config);

  try {
    let rawParams: unknown = {};
    const args = process.argv.slice(2);
    const paramsIdx = args.indexOf("--params");
    if (paramsIdx !== -1 && paramsIdx + 1 < args.length) {
      rawParams = JSON.parse(args[paramsIdx + 1]);
    }
    const params = z.object(TOOL_INPUT_SCHEMA).parse(rawParams) as ToolParams;

    const result = await handleTool(params, clients, profile, config);
    console.log(JSON.stringify(result, null, 2));
  } finally {
    await shutdownClients(clients);
  }
}

/* ------------------------------------------------------------------ */
/*  Entry                                                              */
/* ------------------------------------------------------------------ */

if (isEntrypoint) {
  if (isRunMode) {
    runDirect().catch((err) => {
      console.error(err);
      process.exit(1);
    });
  } else {
    runServer().catch((err) => {
      process.stderr.write(`Fatal: ${err}\n`);
      process.exit(1);
    });
  }
}
