/**
 * Test infrastructure — DO NOT EDIT THIS FILE.
 *
 * Provides fixture factories for generated task app tests.
 *
 * Usage in test files:
 *   import { makeJobserveJob, makeLinkedinJob, makeEmail } from "./test-base.js";
 */

export function makeJobserveJob(overrides?: Record<string, unknown>): Record<string, unknown> {
  return {
    title: "Senior Software Engineer",
    rate: "\u00a3600 PER DAY",
    location: "London",
    duration: "6 months",
    ir35: "Outside IR35",
    agency: "Test Agency",
    ref: "TEST-001",
    tech: ["Python", "Azure"],
    applyUrl: "https://example.com/apply",
    specUrl: "https://example.com/spec",
    body: "Test job description with Python and Azure skills.",
    date: "Mon, 02 Mar 2026",
    subject: "Test Subject",
    from: "test@example.com",
    source: "jobserve",
    ...overrides,
  };
}

export function makeLinkedinJob(overrides?: Record<string, unknown>): Record<string, unknown> {
  return {
    title: "AI Engineer",
    company: "Test Corp",
    location: "London, United Kingdom",
    posted: "2 days ago",
    salary: "",
    url: "https://linkedin.com/jobs/view/test-123",
    detail: {
      title: "AI Engineer",
      company: "Test Corp",
      location: "London, United Kingdom",
      description: "Test job description with LLM and agent skills.",
      url: "https://linkedin.com/jobs/view/test-123",
    },
    source: "linkedin",
    ...overrides,
  };
}

export function makeEmail(
  subject = "Test Alert",
  body = "",
  overrides?: Record<string, unknown>,
): Record<string, unknown> {
  return {
    messageId: "msg-test-001",
    from: "alerts@example.com",
    to: "user@example.com",
    date: "Mon, 02 Mar 2026 10:00:00 +0000",
    subject,
    body,
    ...overrides,
  };
}
