/**
 * Typed wrappers for MCP tools. Each function knows its server, handles errors, and returns parsed data.
 *
 * DO NOT EDIT THIS FILE.
 */

import type { McpClient } from "./mcp-client.js";

export type Clients = Record<string, McpClient>;

function get(clients: Clients, server: string): McpClient {
  const client = clients[server];
  if (!client) throw new Error(`MCP server '${server}' not connected`);
  return client;
}

// ---------------------------------------------------------------------------
// Google — Gmail
// ---------------------------------------------------------------------------

export async function gmailSearch(
  clients: Clients, query: string, maxResults = 10,
): Promise<Array<Record<string, string>>> {
  const result = await get(clients, "google").callTool("gmail_search", { query, maxResults });
  if (result && typeof result === "object" && !Array.isArray(result)) {
    return ((result as Record<string, unknown>)["messages"] as Array<Record<string, string>>) ?? [];
  }
  if (typeof result === "string") return parseGmailSearchText(result);
  return [];
}

export async function gmailRead(
  clients: Clients, messageId: string,
): Promise<Record<string, string> | null> {
  const result = await get(clients, "google").callTool("gmail_read", { messageId });
  if (result && typeof result === "object" && !Array.isArray(result)) {
    return result as Record<string, string>;
  }
  if (typeof result === "string" && result.trim()) {
    return parseGmailReadText(messageId, result);
  }
  return null;
}

function parseGmailSearchText(text: string): Array<Record<string, string>> {
  if (!text.trim() || text.includes("No emails found")) return [];
  const messages: Array<Record<string, string>> = [];
  let current: Record<string, string> = {};
  for (const line of text.split("\n")) {
    const stripped = line.trim();
    if (line.startsWith("ID: ")) {
      if (Object.keys(current).length > 0) messages.push(current);
      current = { id: line.slice(4).trim() };
    } else if (stripped.startsWith("Date: ") && current["id"]) {
      current["date"] = stripped.slice(6);
    } else if (stripped.startsWith("From: ") && current["id"]) {
      current["from"] = stripped.slice(6);
    } else if (stripped.startsWith("Subject: ") && current["id"]) {
      current["subject"] = stripped.slice(9);
    } else if (stripped.startsWith("Snippet: ") && current["id"]) {
      current["snippet"] = stripped.slice(9);
    }
  }
  if (Object.keys(current).length > 0) messages.push(current);
  return messages;
}

function parseGmailReadText(messageId: string, text: string): Record<string, string> {
  const headers: Record<string, string> = {};
  const lines = text.split("\n");
  let bodyStart = 0;
  for (let i = 0; i < lines.length; i++) {
    if (lines[i].trim() === "") { bodyStart = i + 1; break; }
    for (const key of ["From", "To", "Date", "Subject"]) {
      if (lines[i].startsWith(`${key}: `)) {
        headers[key.toLowerCase()] = lines[i].slice(key.length + 2);
        break;
      }
    }
  }
  const body = lines.slice(bodyStart).join("\n").trim();
  return {
    messageId,
    from: headers["from"] ?? "",
    to: headers["to"] ?? "",
    date: headers["date"] ?? "",
    subject: headers["subject"] ?? "",
    body,
  };
}

export async function gmailSend(
  clients: Clients, to: string, subject: string, body: string,
): Promise<string> {
  const result = await get(clients, "google").callTool("gmail_send", { to, subject, body });
  return typeof result === "string" ? result : String(result);
}

// ---------------------------------------------------------------------------
// Google — Calendar
// ---------------------------------------------------------------------------

export async function calendarList(
  clients: Clients,
  options?: { timeMin?: string; timeMax?: string; query?: string; maxResults?: number },
): Promise<string> {
  const args: Record<string, unknown> = { maxResults: options?.maxResults ?? 10 };
  if (options?.timeMin) args["timeMin"] = options.timeMin;
  if (options?.timeMax) args["timeMax"] = options.timeMax;
  if (options?.query) args["query"] = options.query;
  const result = await get(clients, "google").callTool("calendar_list_events", args);
  return typeof result === "string" ? result : String(result);
}

export async function calendarCreate(
  clients: Clients,
  summary: string, start: string, end: string,
  options?: { description?: string; location?: string },
): Promise<string> {
  const args: Record<string, unknown> = { summary, start, end };
  if (options?.description) args["description"] = options.description;
  if (options?.location) args["location"] = options.location;
  const result = await get(clients, "google").callTool("calendar_create_event", args);
  return typeof result === "string" ? result : String(result);
}

export async function calendarGet(
  clients: Clients, eventId: string, calendarId = "primary",
): Promise<string> {
  const result = await get(clients, "google").callTool("calendar_get_event", { eventId, calendarId });
  return typeof result === "string" ? result : String(result);
}

// ---------------------------------------------------------------------------
// Google — Contacts
// ---------------------------------------------------------------------------

export async function contactsSearch(
  clients: Clients, query: string, maxResults = 10,
): Promise<string> {
  const result = await get(clients, "google").callTool("contacts_search", { query, pageSize: maxResults });
  return typeof result === "string" ? result : String(result);
}

export async function contactsList(
  clients: Clients,
  options?: { pageSize?: number; pageToken?: string; sortOrder?: string },
): Promise<string> {
  const args: Record<string, unknown> = { pageSize: options?.pageSize ?? 10 };
  if (options?.pageToken) args["pageToken"] = options.pageToken;
  if (options?.sortOrder) args["sortOrder"] = options.sortOrder;
  const result = await get(clients, "google").callTool("contacts_list", args);
  return typeof result === "string" ? result : String(result);
}

export async function contactsGet(
  clients: Clients, resourceName: string,
): Promise<string> {
  const result = await get(clients, "google").callTool("contacts_get", { resourceName });
  return typeof result === "string" ? result : String(result);
}

export async function contactsCreate(
  clients: Clients,
  givenName: string,
  options?: {
    familyName?: string; email?: string; emailType?: string;
    phone?: string; phoneType?: string; organization?: string; jobTitle?: string;
  },
): Promise<string> {
  const args: Record<string, unknown> = {
    givenName,
    emailType: options?.emailType ?? "other",
    phoneType: options?.phoneType ?? "other",
  };
  if (options?.familyName) args["familyName"] = options.familyName;
  if (options?.email) args["email"] = options.email;
  if (options?.phone) args["phone"] = options.phone;
  if (options?.organization) args["organization"] = options.organization;
  if (options?.jobTitle) args["jobTitle"] = options.jobTitle;
  const result = await get(clients, "google").callTool("contacts_create", args);
  return typeof result === "string" ? result : String(result);
}

export async function contactsUpdate(
  clients: Clients,
  resourceName: string, etag: string,
  options?: {
    givenName?: string; familyName?: string; email?: string; emailType?: string;
    phone?: string; phoneType?: string; organization?: string; jobTitle?: string;
  },
): Promise<string> {
  const args: Record<string, unknown> = {
    resourceName, etag,
    emailType: options?.emailType ?? "other",
    phoneType: options?.phoneType ?? "other",
  };
  if (options?.givenName) args["givenName"] = options.givenName;
  if (options?.familyName) args["familyName"] = options.familyName;
  if (options?.email) args["email"] = options.email;
  if (options?.phone) args["phone"] = options.phone;
  if (options?.organization) args["organization"] = options.organization;
  if (options?.jobTitle) args["jobTitle"] = options.jobTitle;
  const result = await get(clients, "google").callTool("contacts_update", args);
  return typeof result === "string" ? result : String(result);
}

export async function contactsDelete(
  clients: Clients, resourceName: string,
): Promise<string> {
  const result = await get(clients, "google").callTool("contacts_delete", { resourceName });
  return typeof result === "string" ? result : String(result);
}

// ---------------------------------------------------------------------------
// LinkedIn
// ---------------------------------------------------------------------------

export async function linkedinSearch(
  clients: Clients,
  keyword: string,
  options?: {
    location?: string; dateSincePosted?: string; jobType?: string;
    experienceLevel?: string; limit?: number; sortBy?: string;
  },
): Promise<Array<Record<string, unknown>>> {
  const args: Record<string, unknown> = {
    keyword,
    location: options?.location ?? "United Kingdom",
    dateSincePosted: options?.dateSincePosted ?? "past week",
    experienceLevel: options?.experienceLevel ?? "senior",
    limit: options?.limit ?? 10,
    sortBy: options?.sortBy ?? "recent",
  };
  if (options?.jobType) args["jobType"] = options.jobType;
  const result = await get(clients, "linkedin").callTool("linkedin_jobs", args);
  if (typeof result === "string") return [];
  return ((result as Record<string, unknown>)["jobs"] as Array<Record<string, unknown>>) ?? [];
}

export async function linkedinDetail(
  clients: Clients, url: string,
): Promise<Record<string, unknown> | null> {
  const result = await get(clients, "linkedin").callTool("linkedin_job_detail", { url });
  if (typeof result === "string") return null;
  return result as Record<string, unknown>;
}

export async function linkedinSearchWithDetails(
  clients: Clients,
  keyword: string,
  options?: {
    limit?: number; batchSize?: number; delay?: number;
    location?: string; dateSincePosted?: string; jobType?: string;
    experienceLevel?: string; sortBy?: string;
  },
): Promise<Array<Record<string, unknown>>> {
  const { batchSize = 2, delay = 2000, ...searchOpts } = options ?? {};
  const jobs = await linkedinSearch(clients, keyword, searchOpts);
  if (jobs.length === 0) return [];

  const enriched: Array<Record<string, unknown>> = [];
  for (let i = 0; i < jobs.length; i += batchSize) {
    if (i > 0) await new Promise((r) => setTimeout(r, delay));
    const batch = jobs.slice(i, i + batchSize);
    const results = await Promise.all(
      batch.map(async (job) => {
        const url = job["url"] as string | undefined;
        if (!url) return { ...job, detail: {} };
        const detail = await linkedinDetail(clients, url);
        return { ...job, detail: detail ?? {} };
      }),
    );
    enriched.push(...results);
  }
  return enriched;
}

// ---------------------------------------------------------------------------
// Web
// ---------------------------------------------------------------------------

export async function webSearch(
  clients: Clients, query: string, count = 5,
): Promise<Array<Record<string, unknown>>> {
  const result = await get(clients, "web").callTool("web_search", { query, count });
  if (typeof result === "string") return [];
  return ((result as Record<string, unknown>)["results"] as Array<Record<string, unknown>>) ?? [];
}

export async function webFetch(
  clients: Clients, url: string, maxChars = 50000,
): Promise<Record<string, unknown> | null> {
  const result = await get(clients, "web").callTool("web_fetch", { url, maxChars });
  if (typeof result === "string") return null;
  return result as Record<string, unknown>;
}

// ---------------------------------------------------------------------------
// Filesystem
// ---------------------------------------------------------------------------

export async function fsRead(
  clients: Clients, path: string,
): Promise<string | null> {
  const result = await get(clients, "filesystem").callTool("read_file", { path });
  if (typeof result === "string") return result;
  return ((result as Record<string, unknown>)["content"] as string) ?? null;
}

export async function fsWrite(
  clients: Clients, path: string, content: string,
): Promise<boolean> {
  const result = await get(clients, "filesystem").callTool("write_file", { path, content });
  if (result && typeof result === "object") {
    return ((result as Record<string, unknown>)["success"] as boolean) ?? false;
  }
  return false;
}

export async function fsBash(
  clients: Clients, command: string,
): Promise<{ stdout: string; stderr: string; exitCode: number }> {
  const result = await get(clients, "filesystem").callTool("bash", { command });
  if (typeof result === "string") {
    return { stdout: result, stderr: "", exitCode: 0 };
  }
  const r = result as Record<string, unknown>;
  return {
    stdout: (r["stdout"] as string) ?? "",
    stderr: (r["stderr"] as string) ?? "",
    exitCode: (r["exit_code"] as number) ?? 0,
  };
}

// ---------------------------------------------------------------------------
// GitHub
// ---------------------------------------------------------------------------

export async function githubListRepos(
  clients: Clients,
  options?: { owner?: string; type?: string; sort?: string; maxResults?: number },
): Promise<Array<Record<string, unknown>>> {
  const args: Record<string, unknown> = {
    type: options?.type ?? "all",
    sort: options?.sort ?? "updated",
    maxResults: options?.maxResults ?? 10,
  };
  if (options?.owner) args["owner"] = options.owner;
  const result = await get(clients, "github").callTool("list_repos", args);
  if (result && typeof result === "object") {
    return ((result as Record<string, unknown>)["repos"] as Array<Record<string, unknown>>) ?? [];
  }
  return [];
}

export async function githubGetFile(
  clients: Clients, repo: string, path: string, ref?: string,
): Promise<Record<string, unknown>> {
  const args: Record<string, unknown> = { repo, path };
  if (ref) args["ref"] = ref;
  const result = await get(clients, "github").callTool("get_file", args);
  if (result && typeof result === "object" && !Array.isArray(result)) {
    return result as Record<string, unknown>;
  }
  return { type: "file", repo, path, content: typeof result === "string" ? result : "" };
}

export async function githubSearchCode(
  clients: Clients, query: string,
  options?: { repo?: string; language?: string; maxResults?: number },
): Promise<Array<Record<string, unknown>>> {
  const args: Record<string, unknown> = { query, maxResults: options?.maxResults ?? 10 };
  if (options?.repo) args["repo"] = options.repo;
  if (options?.language) args["language"] = options.language;
  const result = await get(clients, "github").callTool("search_code", args);
  if (result && typeof result === "object") {
    return ((result as Record<string, unknown>)["results"] as Array<Record<string, unknown>>) ?? [];
  }
  return [];
}

export async function githubListPrs(
  clients: Clients,
  options?: { repo?: string; state?: string; author?: string; maxResults?: number },
): Promise<Array<Record<string, unknown>>> {
  const args: Record<string, unknown> = {
    state: options?.state ?? "open",
    maxResults: options?.maxResults ?? 10,
  };
  if (options?.repo) args["repo"] = options.repo;
  if (options?.author) args["author"] = options.author;
  const result = await get(clients, "github").callTool("list_prs", args);
  if (result && typeof result === "object") {
    return ((result as Record<string, unknown>)["prs"] as Array<Record<string, unknown>>) ?? [];
  }
  return [];
}

export async function githubGetPr(
  clients: Clients, repo: string, number: number,
): Promise<Record<string, unknown>> {
  const result = await get(clients, "github").callTool("get_pr", { repo, number });
  if (result && typeof result === "object" && !Array.isArray(result)) {
    return result as Record<string, unknown>;
  }
  return { number, title: "", state: "", url: "" };
}

export async function githubCreatePr(
  clients: Clients,
  repo: string, title: string, head: string,
  options?: { body?: string; base?: string; draft?: boolean },
): Promise<Record<string, unknown>> {
  const args: Record<string, unknown> = {
    repo, title, head,
    base: options?.base ?? "main",
    draft: options?.draft ?? false,
  };
  if (options?.body) args["body"] = options.body;
  const result = await get(clients, "github").callTool("create_pr", args);
  if (result && typeof result === "object" && !Array.isArray(result)) {
    return result as Record<string, unknown>;
  }
  return { number: 0, title, head, base: options?.base ?? "main", url: "" };
}

export async function githubListIssues(
  clients: Clients,
  options?: { repo?: string; state?: string; labels?: string; query?: string; maxResults?: number },
): Promise<Array<Record<string, unknown>>> {
  const args: Record<string, unknown> = {
    state: options?.state ?? "open",
    maxResults: options?.maxResults ?? 10,
  };
  if (options?.repo) args["repo"] = options.repo;
  if (options?.labels) args["labels"] = options.labels;
  if (options?.query) args["query"] = options.query;
  const result = await get(clients, "github").callTool("list_issues", args);
  if (result && typeof result === "object") {
    return ((result as Record<string, unknown>)["issues"] as Array<Record<string, unknown>>) ?? [];
  }
  return [];
}

export async function githubCreateIssue(
  clients: Clients,
  repo: string, title: string,
  options?: { body?: string; labels?: string[]; assignees?: string[] },
): Promise<Record<string, unknown>> {
  const args: Record<string, unknown> = { repo, title };
  if (options?.body) args["body"] = options.body;
  if (options?.labels) args["labels"] = options.labels;
  if (options?.assignees) args["assignees"] = options.assignees;
  const result = await get(clients, "github").callTool("create_issue", args);
  if (result && typeof result === "object" && !Array.isArray(result)) {
    return result as Record<string, unknown>;
  }
  return { number: 0, title, url: "", labels: options?.labels ?? [] };
}

// ---------------------------------------------------------------------------
// Anthropic Admin
// ---------------------------------------------------------------------------

export async function anthropicUsage(
  clients: Clients,
  action: string, startingAt: string,
  options?: { endingAt?: string; bucketWidth?: string; groupBy?: string[]; limit?: number },
): Promise<string> {
  const args: Record<string, unknown> = { action, starting_at: startingAt };
  if (options?.endingAt) args["ending_at"] = options.endingAt;
  if (options?.bucketWidth) args["bucket_width"] = options.bucketWidth;
  if (options?.groupBy) args["group_by"] = options.groupBy;
  if (options?.limit != null) args["limit"] = options.limit;
  const result = await get(clients, "anthropic-admin").callTool("anthropic_usage", args);
  return typeof result === "string" ? result : String(result);
}

// ---------------------------------------------------------------------------
// Interview Assist — Analysis
// ---------------------------------------------------------------------------

export async function iaHealthcheck(
  clients: Clients, repoPath?: string,
): Promise<string> {
  const args: Record<string, unknown> = {};
  if (repoPath) args["repo_path"] = repoPath;
  const result = await get(clients, "interview-assist").callTool("ia_healthcheck", args);
  return typeof result === "string" ? result : String(result);
}

export async function iaListRecordings(
  clients: Clients, limit = 30, repoPath?: string,
): Promise<string> {
  const args: Record<string, unknown> = { limit };
  if (repoPath) args["repo_path"] = repoPath;
  const result = await get(clients, "interview-assist").callTool("ia_list_recordings", args);
  return typeof result === "string" ? result : String(result);
}

export async function iaAnalyzeSession(
  clients: Clients, sessionFile: string,
  options?: { repoPath?: string; timeoutSeconds?: number },
): Promise<string> {
  const args: Record<string, unknown> = {
    session_file: sessionFile,
    timeout_seconds: options?.timeoutSeconds ?? 900,
  };
  if (options?.repoPath) args["repo_path"] = options.repoPath;
  const result = await get(clients, "interview-assist").callTool("ia_analyze_session", args);
  return typeof result === "string" ? result : String(result);
}

export async function iaEvaluateSession(
  clients: Clients, sessionFile: string,
  options?: {
    outputFile?: string; model?: string; groundTruthFile?: string;
    repoPath?: string; timeoutSeconds?: number;
  },
): Promise<string> {
  const args: Record<string, unknown> = {
    session_file: sessionFile,
    timeout_seconds: options?.timeoutSeconds ?? 1800,
  };
  if (options?.outputFile) args["output_file"] = options.outputFile;
  if (options?.model) args["model"] = options.model;
  if (options?.groundTruthFile) args["ground_truth_file"] = options.groundTruthFile;
  if (options?.repoPath) args["repo_path"] = options.repoPath;
  const result = await get(clients, "interview-assist").callTool("ia_evaluate_session", args);
  return typeof result === "string" ? result : String(result);
}

export async function iaCompareStrategies(
  clients: Clients, sessionFile: string,
  options?: { outputFile?: string; repoPath?: string; timeoutSeconds?: number },
): Promise<string> {
  const args: Record<string, unknown> = {
    session_file: sessionFile,
    timeout_seconds: options?.timeoutSeconds ?? 1800,
  };
  if (options?.outputFile) args["output_file"] = options.outputFile;
  if (options?.repoPath) args["repo_path"] = options.repoPath;
  const result = await get(clients, "interview-assist").callTool("ia_compare_strategies", args);
  return typeof result === "string" ? result : String(result);
}

export async function iaTuneThreshold(
  clients: Clients, sessionFile: string,
  options?: { optimize?: string; repoPath?: string; timeoutSeconds?: number },
): Promise<string> {
  const args: Record<string, unknown> = {
    session_file: sessionFile,
    optimize: options?.optimize ?? "f1",
    timeout_seconds: options?.timeoutSeconds ?? 1800,
  };
  if (options?.repoPath) args["repo_path"] = options.repoPath;
  const result = await get(clients, "interview-assist").callTool("ia_tune_threshold", args);
  return typeof result === "string" ? result : String(result);
}

export async function iaRegressionTest(
  clients: Clients, baselineFile: string, dataFile: string,
  options?: { repoPath?: string; timeoutSeconds?: number },
): Promise<string> {
  const args: Record<string, unknown> = {
    baseline_file: baselineFile,
    data_file: dataFile,
    timeout_seconds: options?.timeoutSeconds ?? 1800,
  };
  if (options?.repoPath) args["repo_path"] = options.repoPath;
  const result = await get(clients, "interview-assist").callTool("ia_regression_test", args);
  return typeof result === "string" ? result : String(result);
}

export async function iaCreateBaseline(
  clients: Clients, dataFile: string, outputFile: string,
  options?: { version?: string; repoPath?: string; timeoutSeconds?: number },
): Promise<string> {
  const args: Record<string, unknown> = {
    data_file: dataFile,
    output_file: outputFile,
    version: options?.version ?? "1.0",
    timeout_seconds: options?.timeoutSeconds ?? 1800,
  };
  if (options?.repoPath) args["repo_path"] = options.repoPath;
  const result = await get(clients, "interview-assist").callTool("ia_create_baseline", args);
  return typeof result === "string" ? result : String(result);
}

export async function iaTranscribeOnce(
  clients: Clients,
  options?: {
    durationSeconds?: number; source?: string;
    micDeviceId?: string; micDeviceName?: string;
    sampleRate?: number; model?: string; language?: string;
    endpointingMs?: number; utteranceEndMs?: number;
    diarize?: boolean; outputFile?: string;
    repoPath?: string; timeoutSeconds?: number;
  },
): Promise<string> {
  const args: Record<string, unknown> = {
    duration_seconds: options?.durationSeconds ?? 8,
    source: options?.source ?? "microphone",
    sample_rate: options?.sampleRate ?? 16000,
    model: options?.model ?? "nova-2",
    language: options?.language ?? "en",
    endpointing_ms: options?.endpointingMs ?? 300,
    utterance_end_ms: options?.utteranceEndMs ?? 1000,
    diarize: options?.diarize ?? false,
    timeout_seconds: options?.timeoutSeconds ?? 180,
  };
  if (options?.micDeviceId) args["mic_device_id"] = options.micDeviceId;
  if (options?.micDeviceName) args["mic_device_name"] = options.micDeviceName;
  if (options?.outputFile) args["output_file"] = options.outputFile;
  if (options?.repoPath) args["repo_path"] = options.repoPath;
  const result = await get(clients, "interview-assist").callTool("ia_transcribe_once", args);
  return typeof result === "string" ? result : String(result);
}

// ---------------------------------------------------------------------------
// Interview Assist — STT Sessions
// ---------------------------------------------------------------------------

export async function sttListDevices(
  clients: Clients, repoPath?: string,
): Promise<string> {
  const args: Record<string, unknown> = {};
  if (repoPath) args["repo_path"] = repoPath;
  const result = await get(clients, "interview-assist").callTool("stt_list_devices", args);
  return typeof result === "string" ? result : String(result);
}

export async function sttStartSession(
  clients: Clients,
  options?: {
    source?: string; micDeviceId?: string; micDeviceName?: string;
    model?: string; language?: string; sampleRate?: number;
    endpointingMs?: number; utteranceEndMs?: number;
    diarize?: boolean; chunkSeconds?: number; repoPath?: string;
  },
): Promise<string> {
  const args: Record<string, unknown> = {
    source: options?.source ?? "microphone",
    model: options?.model ?? "nova-2",
    language: options?.language ?? "en",
    sample_rate: options?.sampleRate ?? 16000,
    endpointing_ms: options?.endpointingMs ?? 300,
    utterance_end_ms: options?.utteranceEndMs ?? 1000,
    diarize: options?.diarize ?? false,
    chunk_seconds: options?.chunkSeconds ?? 4,
  };
  if (options?.micDeviceId) args["mic_device_id"] = options.micDeviceId;
  if (options?.micDeviceName) args["mic_device_name"] = options.micDeviceName;
  if (options?.repoPath) args["repo_path"] = options.repoPath;
  const result = await get(clients, "interview-assist").callTool("stt_start_session", args);
  return typeof result === "string" ? result : String(result);
}

export async function sttGetUpdates(
  clients: Clients, sessionId: string, sinceSeq = 0, limit = 100,
): Promise<string> {
  const result = await get(clients, "interview-assist").callTool("stt_get_updates", {
    session_id: sessionId, since_seq: sinceSeq, limit,
  });
  return typeof result === "string" ? result : String(result);
}

export async function sttGetSession(
  clients: Clients, sessionId: string,
): Promise<string> {
  const result = await get(clients, "interview-assist").callTool("stt_get_session", {
    session_id: sessionId,
  });
  return typeof result === "string" ? result : String(result);
}

export async function sttStopSession(
  clients: Clients, sessionId: string,
): Promise<string> {
  const result = await get(clients, "interview-assist").callTool("stt_stop_session", {
    session_id: sessionId,
  });
  return typeof result === "string" ? result : String(result);
}
